package-lock.json
package.json
toolkits/nature/packages/nature-context/HISTORY.md
toolkits/nature/packages/nature-context/package.json

Last published version did not extend properly and only published the nature files without the global files. Hopefully, by re-pushing this with a bug fix it should publish correctly.
Also fixes bug from last attempt

nature-context v0.18.1

---

toolkits/nature/packages/nature-context/HISTORY.md
toolkits/nature/packages/nature-context/package.json

new version of the package manager

nature-context v0.18.2

---

toolkits/springer/packages/springer-pagination/HISTORY.md
toolkits/springer/packages/springer-pagination/README.md
toolkits/springer/packages/springer-pagination/package.json
toolkits/springer/packages/springer-pagination/scss/10-settings/pagination.scss
toolkits/springer/packages/springer-pagination/scss/50-components/pagination.scss

- Adds background to pagination
- Rename variable names

update pagination to new design

---

toolkits/springer/packages/springer-context/HISTORY.md
toolkits/springer/packages/springer-context/package.json

- fix typo in package description

Bumps global-context extends version to 9.1.2

---

toolkits/springer/packages/springer-listing/HISTORY.md
toolkits/springer/packages/springer-listing/package.json
toolkits/springer/packages/springer-listing/scss/10-settings/listing.scss
toolkits/springer/packages/springer-meta/HISTORY.md
toolkits/springer/packages/springer-meta/package.json
toolkits/springer/packages/springer-meta/scss/10-settings/meta.scss

Use system font for sans serif

---

toolkits/springer/packages/springer-meta/HISTORY.md
toolkits/springer/packages/springer-meta/package.json

0.0.4 didnt seem to get picked up for some reason

Bump package version

---

toolkits/nature/packages/nature-card/HISTORY.md
toolkits/nature/packages/nature-card/package.json
toolkits/springer/packages/springer-card/HISTORY.md
toolkits/springer/packages/springer-card/package.json

for nature-card and springer-card

Bumps global-card extends version to 0.2.0

---

toolkits/springer/packages/springer-user-metadata/HISTORY.md
toolkits/springer/packages/springer-user-metadata/package.json
toolkits/springer/packages/springer-user-metadata/scss/10-settings/user-metadata.scss
toolkits/springer/packages/springer-user-metadata/scss/50-components/user-metadata.scss

and renamed settings to indicate direction for spacing

Use correct settings on component

---

toolkits/springer/packages/springer-header/HISTORY.md
toolkits/springer/packages/springer-header/package.json
toolkits/springer/packages/springer-header/scss/50-components/springer-header.scss

Fixes the amount of space between header items now that the dots have been removed from publisher headers

Adds more margin to header items

---

toolkits/global/packages/global-banner/HISTORY.md
toolkits/global/packages/global-banner/package.json
toolkits/global/packages/global-banner/scss/50-components/_banner.scss

Somehow missed these in a previous version.

global-banner: remove pseudo elements

---

toolkits/nature/packages/nature-context/HISTORY.md
toolkits/nature/packages/nature-context/package.json
toolkits/nature/packages/nature-context/scss/10-settings/colors/default.scss

In this case to use on the coronavirus banner.

Add colours to the range

---

toolkits/global/packages/global-banner/HISTORY.md
toolkits/global/packages/global-banner/README.md
toolkits/global/packages/global-banner/package.json
toolkits/global/packages/global-banner/scss/50-components/_banner.scss

global-banner: set text centre

---

toolkits/springer/packages/springer-ad/HISTORY.md
toolkits/springer/packages/springer-ad/package.json
toolkits/springer/packages/springer-ad/scss/50-components/ad.scss
toolkits/springer/packages/springer-listing/HISTORY.md
toolkits/springer/packages/springer-listing/package.json
toolkits/springer/packages/springer-listing/scss/10-settings/listing.scss
toolkits/springer/packages/springer-meta/HISTORY.md
toolkits/springer/packages/springer-meta/package.json
toolkits/springer/packages/springer-meta/scss/10-settings/meta.scss
toolkits/springer/packages/springer-user-metadata/HISTORY.md
toolkits/springer/packages/springer-user-metadata/package.json
toolkits/springer/packages/springer-user-metadata/scss/50-components/user-metadata.scss

- Removes references to redundant mixins and variables
- Adds peer dependencies which are missing

springer: remove webfont usage

---

toolkits/global/packages/global-context/HISTORY.md
toolkits/global/packages/global-context/README.md
toolkits/global/packages/global-context/package.json
toolkits/global/packages/global-context/scss/10-settings/spacing.scss
toolkits/global/packages/global-context/scss/20-functions/spacing.scss
toolkits/global/packages/global-context/scss/60-utilities/spacing.scss

- Adds function for getting spacing from the `$context--spacing` list
- Adds utilities for margin and padding based off of the `$context--spacing` list

global-context: feature - spacing

---

package-lock.json
package.json

Brings in the change to switch off `prefer-node-append`.

Bump eslint-config version

---

toolkits/springer/packages/springer-dropdown/HISTORY.md
toolkits/springer/packages/springer-dropdown/js/create-dropdown.js
toolkits/springer/packages/springer-dropdown/package.json

- Also fixes typo in function name within same file.

springer-dropdown: Use appendChild instead of append

---

toolkits/nature/packages/nature-context/HISTORY.md
toolkits/nature/packages/nature-context/package.json
toolkits/springer/packages/springer-context/HISTORY.md
toolkits/springer/packages/springer-context/package.json

- Brings in the container defined in global

springer/nature context: bump global-context dependency version

---

toolkits/springer/packages/springer-header/HISTORY.md
toolkits/springer/packages/springer-header/package.json
toolkits/springer/packages/springer-header/scss/50-components/springer-header.scss
toolkits/springer/packages/springer-publisher-footer/HISTORY.md
toolkits/springer/packages/springer-publisher-footer/package.json
toolkits/springer/packages/springer-publisher-footer/scss/50-components/springer-publisher-footer.scss

springer-header
springer-publisher-footer

springer components: Replace container with u-container

---

toolkits/global/packages/global-article/HISTORY.md
toolkits/global/packages/global-article/package.json
toolkits/global/packages/global-article/scss/10-settings/article.scss
toolkits/global/packages/global-article/scss/50-components/article-metrics.scss

Minor adjustments for metrics page focused on the font-sizes and family.

Consolidate metrics page, minor adjusts in fonts

---

toolkits/global/packages/global-forms/scss/40-base/_global-forms.scss

Removes fieldset border as part of global form resets

removes border on fieldset element

---

toolkits/global/packages/global-article/HISTORY.md
toolkits/global/packages/global-article/package.json
toolkits/global/packages/global-article/scss/50-components/article-enhanced.scss

It was a demand from James A.
Note on the changes:
Possibly in the future, there will be a global button so we could remove it from here, but for now, I added these minor changes to force a max-height.

shrink pdf button to a max height

---

toolkits/global/packages/global-autocomplete/HISTORY.md
toolkits/global/packages/global-autocomplete/__tests__/index.js
toolkits/global/packages/global-autocomplete/demo/main.js
toolkits/global/packages/global-autocomplete/js/index.js
toolkits/global/packages/global-autocomplete/package.json

- Enhance arguments with additional `httpMethod` setting
- Enhance arguments with additional `bodyTemplate` setting
- Add support for the two above new settings
- Delegate "No results" to resultsCallBack rather than generateSuggestions
- Update demo
- Update HISTORY
- Bump to next major version because of breaking change
Forked from the PR #154

Global autocomplete: Improve dynamic data support

---

toolkits/global/packages/global-article/HISTORY.md
toolkits/global/packages/global-article/js/authors.js
toolkits/global/packages/global-article/package.json
toolkits/global/packages/global-article/scss/50-components/article-enhanced.scss

Relocate the position of links in the author popup and add a new optional link to view the author publication.
Reposition the ORCID link and some refactoring in some naming to simplicity.
https://github.com/springernature/oscar/issues/1510

#1510 - Add link view authors pub popup

---

toolkits/nature/packages/nature-context/HISTORY.md
toolkits/nature/packages/nature-context/package.json
toolkits/nature/packages/nature-context/scss/10-settings/colors/default.scss
toolkits/springer/packages/springer-context/HISTORY.md
toolkits/springer/packages/springer-context/package.json

bump extendsPackage global-context to 14.2.1

Update springer and nature context 

---

toolkits/global/packages/global-autocomplete/HISTORY.md
toolkits/global/packages/global-autocomplete/__tests__/index.js
toolkits/global/packages/global-autocomplete/demo/main.js
toolkits/global/packages/global-autocomplete/js/index.js
toolkits/global/packages/global-autocomplete/package.json

- Add support for this config setting
- Remove expectation from user to provide data-index on each suggestion element
- Add tests for the new setting
- Update demo accordingly for documentation sake
Closes #186

Add a "selectOnSuggestionBrowsing" config setting

---

toolkits/global/packages/global-button/HISTORY.md
toolkits/global/packages/global-button/package.json
toolkits/global/packages/global-button/scss/10-settings/button.scss
toolkits/global/packages/global-button/scss/50-components/button.scss

add padding to `.c-button--large`

Update global button

---

toolkits/springer/packages/springer-button/HISTORY.md
toolkits/springer/packages/springer-button/package.json
toolkits/springer/packages/springer-button/scss/10-settings/button-springer.scss

- Bump extendsPackage and peerDependencies to latest
- Reduce $button--font-size-large
- Add $button--padding-large
- Change text-align from left to center

Update springer button size and alignment

---

toolkits/nature/packages/nature-button/HISTORY.md
toolkits/nature/packages/nature-button/package.json
toolkits/nature/packages/nature-button/scss/10-settings/button-nature.scss

Add blue color on hover to prevent white text on white background for buttons

Update nature-button color on hover

---

toolkits/global/packages/global-forms/HISTORY.md
toolkits/global/packages/global-forms/package.json
toolkits/global/packages/global-forms/scss/10-settings/_global-forms.scss
toolkits/global/packages/global-forms/scss/50-components/_global-forms.scss

Includes new settings for form labels, making them less prescriptive.

Global form margin

---

toolkits/springer/packages/springer-header/HISTORY.md
toolkits/springer/packages/springer-header/package.json
toolkits/springer/packages/springer-header/scss/10-settings/_header.scss
toolkits/springer/packages/springer-header/scss/50-components/_header.scss

as per tweaks requested by James A in https://jira.springernature.com/browse/PAN-755

Tweaks springer header background colour and bottom border colour

---

toolkits/global/packages/global-javascript/HISTORY.md
toolkits/global/packages/global-javascript/README.md
toolkits/global/packages/global-javascript/__tests__/unit/util/onetrust.spec.js
toolkits/global/packages/global-javascript/package.json
toolkits/global/packages/global-javascript/src/helpers/index.js
toolkits/global/packages/global-javascript/src/helpers/util/onetrust.js

Adds `checkConsent` and `isConsentBannerClosed` utilities.

global-javascript: Adds OneTrust utilities

---

toolkits/global/packages/global-popup/HISTORY.md
toolkits/global/packages/global-popup/package.json
toolkits/global/packages/global-popup/scss/10-settings/_global-popup.scss
toolkits/global/packages/global-popup/scss/50-components/_global-popup.scss

Adds border radius to global popup

---

toolkits/global/packages/global-expander/HISTORY.md
toolkits/global/packages/global-expander/__tests__/expander.spec.js
toolkits/global/packages/global-expander/js/expander.js
toolkits/global/packages/global-expander/package.json

- handle values that are not accepted for AUTOFOCUS
- swap out switch for if/else when detecting values on AUTOFOCUS

handle AUTOFOCUS option in global-expander

---

context/brand-context/HISTORY.md
context/brand-context/default/scss/10-settings/typography.scss
context/brand-context/nature/scss/10-settings/typography.scss
context/brand-context/package.json

Variable will be used if user has save-data/lite mode set to on within there browser.

Add new variable to allow for save data

---

toolkits/global/packages/global-popup/HISTORY.md
toolkits/global/packages/global-popup/package.json

Forgot to bump version in previous PR

Bumps version to 1.0.0

---

toolkits/global/packages/global-popup/HISTORY.md
toolkits/global/packages/global-popup/__tests__/popup.spec.js
toolkits/global/packages/global-popup/js/popup.js
toolkits/global/packages/global-popup/package.json
toolkits/global/packages/global-popup/scss/10-settings/_global-popup.scss
toolkits/global/packages/global-popup/scss/50-components/_global-popup.scss

Forgot to make these changes in a recent PR for Global-Popup. Only makes sense to style the component if js as it's a js-only component.

Improve popup pos calc

---

toolkits/global/packages/global-popup/HISTORY.md
toolkits/global/packages/global-popup/package.json
toolkits/global/packages/global-popup/scss/10-settings/_global-popup.scss
toolkits/global/packages/global-popup/scss/50-components/_global-popup.scss

- Border and box shadow changes requested by James Alegria
- Made sense to me to convert the arrows to css only

Refactor Global Popup styles to tweak box shadow, border and arrow styling

---

toolkits/nature/packages/nature-header/HISTORY.md
toolkits/nature/packages/nature-header/README.md
toolkits/nature/packages/nature-header/package.json
toolkits/nature/packages/nature-header/scss/10-settings/header.scss
toolkits/nature/packages/nature-header/scss/50-components/header-expander.scss
toolkits/nature/packages/nature-header/scss/50-components/header.scss

Add `c-header__site-navigation--last` modifier to remove right padding

Add modifier in nature-header

---

toolkits/springer/packages/springer-lists/HISTORY.md
toolkits/springer/packages/springer-lists/README.md
toolkits/springer/packages/springer-lists/package.json
toolkits/springer/packages/springer-lists/scss/10-settings/_list-columned.scss
toolkits/springer/packages/springer-lists/scss/50-components/_list-columned.scss

moving `c-list-columned` into component from refactor-pandora folder

add c-list-columned to springer-lists

---

toolkits/springer/packages/springer-box/HISTORY.md
toolkits/springer/packages/springer-box/package.json
toolkits/springer/packages/springer-box/scss/10-settings/_box.scss
toolkits/springer/packages/springer-box/scss/50-components/_box.scss

Added these two classes to support the removal of [c-panel](https://github.com/springernature/oscar/tree/master/lib/frontend/src/shared/refactor-pandora/scss/panel) in refactor-pandora folder

Add extra modifiers to springer-box

---

toolkits/nature/packages/nature-footer/HISTORY.md
toolkits/nature/packages/nature-footer/README.md
toolkits/nature/packages/nature-footer/package.json
toolkits/nature/packages/nature-footer/scss/10-settings/footer.scss
toolkits/nature/packages/nature-footer/scss/50-components/footer.scss

First step of moving the nature footer from the nature-150 folder into a shared package.

Add nature footer as a component

---

context/brand-context/HISTORY.md
context/brand-context/default/scss/20-functions/url-encode.scss
context/brand-context/default/scss/30-mixins/arrow.scss
context/brand-context/package.json

Adds a nice arrow mixing for good arrow times

Adds arrow mixin

---

toolkits/global/packages/global-loader-animation/HISTORY.md
toolkits/global/packages/global-loader-animation/README.md
toolkits/global/packages/global-loader-animation/js/index.js
toolkits/global/packages/global-loader-animation/package.json
toolkits/global/packages/global-loader-animation/scss/10-settings/_default.scss
toolkits/global/packages/global-loader-animation/scss/50-components/_loader.scss

Show the loader swirly thing to distract the user from the inevitable void while requests and things are happening.

adds loader animation

---

toolkits/springernature/packages/springernature-user-details/HISTORY.md
toolkits/springernature/packages/springernature-user-details/package.json
toolkits/springernature/packages/springernature-user-details/scss/10-settings/layout.scss
toolkits/springernature/packages/springernature-user-details/scss/50-components/enhanced.scss

Having started to implement this component in another project I have realised it would be useful to make another of the CSS rules configurable.

make z-index configurable

---

toolkits/springernature/packages/springernature-header/HISTORY.md
toolkits/springernature/packages/springernature-header/package.json
toolkits/springernature/packages/springernature-header/scss/50-components/core.scss
toolkits/springernature/packages/springernature-header/scss/50-components/enhanced.scss

Now I have started incorporating this header component into our codebase I have been able to see that a few tweaks are required to the CSS.

Tweak header styles a bit

---

toolkits/nature/packages/nature-hero/HISTORY.md
toolkits/nature/packages/nature-hero/README.md
toolkits/nature/packages/nature-hero/package.json
toolkits/nature/packages/nature-hero/scss/10-settings/hero.scss
toolkits/nature/packages/nature-hero/scss/50-components/hero.scss

Add nature-hero to toolkit

---

toolkits/global/packages/global-meta/HISTORY.md
toolkits/global/packages/global-meta/README.md
toolkits/global/packages/global-meta/package.json
toolkits/global/packages/global-meta/scss/10-settings/_default.scss
toolkits/global/packages/global-meta/scss/10-settings/_nature.scss
toolkits/global/packages/global-meta/scss/50-components/_meta.scss

support removal of nature-meta from lib/frontend

add nature brand to global-meta

---

toolkits/global/packages/global-corporate-footer/HISTORY.md
toolkits/global/packages/global-corporate-footer/package.json
toolkits/global/packages/global-corporate-footer/scss/50-components/corporate-footer.scss
toolkits/global/packages/global-meta/HISTORY.md
toolkits/global/packages/global-meta/package.json
toolkits/global/packages/global-meta/scss/50-components/_meta.scss
toolkits/global/packages/global-status-message/HISTORY.md
toolkits/global/packages/global-status-message/package.json
toolkits/global/packages/global-status-message/scss/50-components/status-message.scss

Replace font-size with existing static value in settings

Remove use of rfs font-size mixin in global components

---

toolkits/springernature/packages/springernature-user-details/HISTORY.md
toolkits/springernature/packages/springernature-user-details/package.json
toolkits/springernature/packages/springernature-user-details/scss/10-settings/colours.scss
toolkits/springernature/packages/springernature-user-details/scss/50-components/enhanced.scss

Arrow should be same colour as text

make arrow color same as text

---

toolkits/global/packages/global-meta/HISTORY.md
toolkits/global/packages/global-meta/package.json
toolkits/global/packages/global-meta/scss/10-settings/_nature.scss

Update Nature settings to match existing c-meta style from app (and support it being removed from nature app)

update nature settings for global-meta

---

README.md

change refs from travis.org to travis.com

Switch from travis.org to travis.com

---

toolkits/springernature/packages/springernature-header/HISTORY.md
toolkits/springernature/packages/springernature-header/package.json
toolkits/springernature/packages/springernature-header/scss/50-components/enhanced.scss
toolkits/springernature/packages/springernature-header/view/header.hbs

Fix to the border colour rule
Tweak to template to make it more generic

Fix color sn header

---

toolkits/springernature/packages/springernature-user-details/HISTORY.md
toolkits/springernature/packages/springernature-user-details/README.md
toolkits/springernature/packages/springernature-user-details/package.json

The code example was missing `springernature-` from the filenames

Updates documentation

---

toolkits/springernature/packages/springernature-user-details/HISTORY.md
toolkits/springernature/packages/springernature-user-details/README.md
toolkits/springernature/packages/springernature-user-details/package.json
toolkits/springernature/packages/springernature-user-details/scss/10-settings/colours.scss
toolkits/springernature/packages/springernature-user-details/scss/50-components/core.scss
toolkits/springernature/packages/springernature-user-details/scss/50-components/enhanced.scss

Use the colors from the springernature context, update readme to add missing dep

Upadate colors user detail

---

toolkits/global/packages/global-pill/HISTORY.md
toolkits/global/packages/global-pill/README.md
toolkits/global/packages/global-pill/package.json
toolkits/global/packages/global-pill/scss/10-settings/default.scss
toolkits/global/packages/global-pill/scss/10-settings/nature.scss
toolkits/global/packages/global-pill/scss/50-components/pill.scss

Adds pill scss component to global toolkit

---

toolkits/springernature/packages/springernature-user-details/HISTORY.md
toolkits/springernature/packages/springernature-user-details/README.md
toolkits/springernature/packages/springernature-user-details/package.json
toolkits/springernature/packages/springernature-user-details/scss/50-components/enhanced.scss

Fix syntax for map-get
Update readme to remove unnecessary deps

fix css syntax and update readme

---

toolkits/springer/packages/springer-box/HISTORY.md
toolkits/springer/packages/springer-box/package.json
toolkits/springer/packages/springer-box/scss/50-components/_box.scss
toolkits/springer/packages/springer-listing/HISTORY.md
toolkits/springer/packages/springer-listing/package.json
toolkits/springer/packages/springer-listing/scss/50-components/_listing.scss
toolkits/springer/packages/springer-user-metadata/HISTORY.md
toolkits/springer/packages/springer-user-metadata/scss/50-components/_user-metadata.scss

Replace font-size with existing static value in settings
https://trello.com/c/5Mfbn6Tv

remove rfs mixin from springer packages

---

context/brand-context/HISTORY.md
context/brand-context/default/scss/10-settings/typography.scss
context/brand-context/default/scss/60-utilities/typography.scss
context/brand-context/package.json
context/brand-context/springer/scss/10-settings/typography.scss
context/brand-context/springer/scss/60-utilities/typography.scss

... and remove from Springer brand

Move font-weight utilities to default context

---

toolkits/nature/packages/nature-header/HISTORY.md
toolkits/nature/packages/nature-header/README.md
toolkits/nature/packages/nature-header/package.json
toolkits/nature/packages/nature-header/scss/50-components/header-expander.scss
toolkits/nature/packages/nature-header/scss/50-components/header.scss

https://jira.springernature.com/browse/PAN-1068

Tidy up nature-header at narrow screen widths

---

toolkits/global/packages/global-pagination/HISTORY.md
toolkits/global/packages/global-pagination/README.md
toolkits/global/packages/global-pagination/package.json
toolkits/global/packages/global-pagination/scss/10-settings/default.scss
toolkits/global/packages/global-pagination/scss/50-components/pagination.scss

Move the `springer-pagination` into `global `

add pagination to global component

---

context/brand-context/default/scss/30-mixins/links.scss
toolkits/global/packages/global-lists/HISTORY.md
toolkits/global/packages/global-lists/README.md
toolkits/global/packages/global-lists/package.json
toolkits/global/packages/global-lists/scss/10-settings/_default.scss
toolkits/global/packages/global-lists/scss/10-settings/_springer.scss
toolkits/global/packages/global-lists/scss/10-settings/_springernature.scss
toolkits/global/packages/global-lists/scss/50-components/_list-columned.scss
toolkits/global/packages/global-lists/scss/50-components/_list-description.scss
toolkits/global/packages/global-lists/scss/50-components/_list-group.scss

- Add springernature theme
- Rename mixin `interface-link` to `u-link-interface`and move it to global brand-context

Move springer-lists component to global

---

toolkits/global/packages/global-expander/HISTORY.md
toolkits/global/packages/global-expander/__tests__/expander.spec.js
toolkits/global/packages/global-expander/js/expander.js
toolkits/global/packages/global-expander/package.json

Issues raised from nature VPAT review:
https://jira.springernature.com/browse/PAN-1145
https://jira.springernature.com/browse/PAN-1147

remove aria-pressed and replace aria-hidden with hidden attribute in global-expander

---

toolkits/springernature/packages/springernature-header/HISTORY.md
toolkits/springernature/packages/springernature-header/package.json
toolkits/springernature/packages/springernature-header/scss/50-components/core.scss
toolkits/springernature/packages/springernature-header/scss/50-components/enhanced.scss

Updates media queries to reflect springer nature brand context rather than default brand context

Updates media queries

---

toolkits/springernature/packages/springernature-header/HISTORY.md
toolkits/springernature/packages/springernature-header/package.json
toolkits/springernature/packages/springernature-header/scss/50-components/core.scss
toolkits/springernature/packages/springernature-header/scss/50-components/enhanced.scss

Sn header component update color map

---

context/brand-context/HISTORY.md
context/brand-context/package.json
context/brand-context/springernature/scss/30-mixins/typography.scss

Fix for some inconsistency in the variable names that was causing problems with my build

Updates font-size variable name in typography mixin

---

context/brand-context/HISTORY.md
context/brand-context/package.json
context/brand-context/springernature/scss/10-settings/buttons.scss

Delete inherit from box-shadow property on hover since it doesn't really inherit anything 🙈

[NM, MC] Fix button box-shadow on hover for Springernature brand

---

toolkits/nature/packages/nature-hero/HISTORY.md
toolkits/nature/packages/nature-hero/package.json
toolkits/nature/packages/nature-hero/scss/50-components/hero.scss

bugbash item: https://trello.com/c/ZjjBiBq4/46-ie10-hero-image-does-not-appear-in-ie10

Fix nature-hero image not appearing in IE10

---

toolkits/global/packages/global-popup/HISTORY.md
toolkits/global/packages/global-popup/package.json
toolkits/nature/packages/nature-header/HISTORY.md
toolkits/nature/packages/nature-header/package.json

* Bump global-expander to 4.0.1
* Bump global-javascript to 3.0.1

Bump deps in global-popup and nature-header

---

toolkits/global/packages/global-article/HISTORY.md
toolkits/global/packages/global-article/package.json

* Bump global-expander to 4.0.1
* Bump global-javascript to 3.0.1

update deps in global-article

---

context/brand-context/HISTORY.md
context/brand-context/default/scss/10-settings/typography.scss
context/brand-context/default/scss/30-mixins/typography.scss
context/brand-context/nature/scss/30-mixins/typography.scss
context/brand-context/package.json
context/brand-context/springer/scss/30-mixins/typography.scss
context/brand-context/springernature/scss/30-mixins/typography.scss

This PR prepares the brand context to welcome the global-card component with the option of choosing what kind of heading style to include on it.

[NM] Use placeholders for u-h* mixins

---

toolkits/global/packages/global-card/HISTORY.md
toolkits/global/packages/global-card/package.json
toolkits/global/packages/global-card/scss/10-settings/default.scss
toolkits/global/packages/global-card/scss/10-settings/springernature.scss
toolkits/global/packages/global-card/scss/50-components/card.scss

- Add new card--title-heading parameter
- Use the new u-heading mixin with the parameter as argument
- Add a default and SN value for the parameter
- Adjust to the new brand-context

[NM] New heading mixin for card title

---

context/brand-context/HISTORY.md
context/brand-context/package.json
context/brand-context/springernature/scss/30-mixins/typography.scss

@foxintherain asked all of the heading styles in SN to use serif font family

[NM] change font family for SN h4,h5 mixins

---

toolkits/nature/packages/nature-hero/HISTORY.md
toolkits/nature/packages/nature-hero/README.md
toolkits/nature/packages/nature-hero/package.json

- update to `brand-context@10.1.3`
- Update README

nature-hero: update to the latest context version

---

toolkits/nature/packages/nature-header/HISTORY.md
toolkits/nature/packages/nature-header/README.md
toolkits/nature/packages/nature-header/package.json
toolkits/nature/packages/nature-header/scss/50-components/header.scss

Also update readme to reflect what is on live and remove two dropdown examples didnt show anything different.

Capitalize first letter instead all words in links

---

DEPRECATED.md
toolkits/nature/packages/nature-header/HISTORY.md
toolkits/nature/packages/nature-header/js/enhanced-header.js
toolkits/nature/packages/nature-header/package.json

https://jira.springernature.com/browse/PAN-1214
* Add autofocus option to first tabbable element
* Bump brand-context version
* update global-button location on DEPRECATED.md

autofocus on search input when user clicks on search

---

context/brand-context/HISTORY.md
context/brand-context/nature/scss/10-settings/typography.scss
context/brand-context/nature/scss/30-mixins/typography.scss
context/brand-context/package.json

Adjust font-size, line-height and letter-spacing based on https://github.com/springernature/ux-elements-docs/blob/master/nature/styleguide/typography.md
PR for component changes to come after this 😬

Add fluid typography for headings to nature brand

---

toolkits/global/packages/global-javascript/HISTORY.md
toolkits/global/packages/global-javascript/package.json
toolkits/global/packages/global-javascript/src/helpers/util/make-array.js

I think the generated code for for .. of _may_ also be breaking phantomjs in the critical css script

Replace use of for of loop to create a smaller transpiled bundle

---

context/brand-context/HISTORY.md
context/brand-context/nature/scss/30-mixins/typography.scss
context/brand-context/package.json
toolkits/nature/packages/nature-header/HISTORY.md
toolkits/nature/packages/nature-header/package.json

Add static value fallback for fluid typography on nature headings

fallback for fluid typography on nature headings

---

context/brand-context/HISTORY.md
context/brand-context/nature/scss/30-mixins/typography.scss
context/brand-context/package.json

previously line-height and letter-spacing in the wrong order 🤦

fix fallback typography on headings

---

toolkits/springernature/packages/springernature-header/HISTORY.md
toolkits/springernature/packages/springernature-header/package.json
toolkits/springernature/packages/springernature-header/view/header.hbs

Use new branding URL

---

context/brand-context/HISTORY.md
context/brand-context/package.json
context/brand-context/springernature/scss/40-base/forms.scss
context/brand-context/springernature/scss/enhanced.scss

This is a first step toward add Springer Nature branded forms package (see #518)

Add base layer for Springer Nature forms

---

context/package-manager.json
package-lock.json
package.json
toolkits/global/packages/global-skip-link/HISTORY.md
toolkits/global/packages/global-skip-link/README.md
toolkits/global/packages/global-skip-link/package.json
toolkits/global/packages/global-skip-link/scss/10-settings/_default.scss
toolkits/global/packages/global-skip-link/scss/10-settings/_nature.scss
toolkits/global/packages/global-skip-link/scss/10-settings/_springernature.scss
toolkits/global/packages/global-skip-link/scss/50-components/_skip-link.scss
toolkits/package-manager.json
toolkits/springernature/packages/springernature-forms/HISTORY.md
toolkits/springernature/packages/springernature-forms/README.md
toolkits/springernature/packages/springernature-forms/demo/dist/index.html
toolkits/springernature/packages/springernature-forms/demo/index.hbs
toolkits/springernature/packages/springernature-forms/package.json

This should help approaching skip links consistently across the company.
I avoided using absolute positioning with top, left values since this method creates problems for some screen readers.
In SN it looks like this:

New skip-link toolkit

---

toolkits/global/packages/global-pill/HISTORY.md
toolkits/global/packages/global-pill/README.md
toolkits/global/packages/global-pill/package.json
toolkits/global/packages/global-pill/scss/10-settings/nature.scss
toolkits/global/packages/global-pill/scss/50-components/pill.scss

* Add default settings and to nature settings
* Add overrides for margin values to nature settings
* Add border to increase contrast from background
* Update branding info and example in readme

Add border to global-pill to increase contrast

---

toolkits/springernature/packages/springernature-submission-header/HISTORY.md
toolkits/springernature/packages/springernature-submission-header/README.md
toolkits/springernature/packages/springernature-submission-header/package.json
toolkits/springernature/packages/springernature-submission-header/scss/50-components/core.scss
toolkits/springernature/packages/springernature-submission-header/scss/50-components/enhanced.scss
toolkits/springernature/packages/springernature-submission-header/view/header.hbs

Hello.
'Submission details tab' component.

Create submission details header component

---

toolkits/springernature/packages/springernature-submission-header/HISTORY.md
toolkits/springernature/packages/springernature-submission-header/README.md
toolkits/springernature/packages/springernature-submission-header/package.json
toolkits/springernature/packages/springernature-submission-header/view/header.hbs

Adds Files section to template, and download-all link. 
Changes the colour of the dropdown arrow.

Tweak colours, and template

---

toolkits/springernature/packages/springernature-submission-header/HISTORY.md
toolkits/springernature/packages/springernature-submission-header/README.md
toolkits/springernature/packages/springernature-submission-header/package.json
toolkits/springernature/packages/springernature-submission-header/scss/50-components/enhanced.scss
toolkits/springernature/packages/springernature-submission-header/view/header.hbs

Having moved this component from the project into frontend components, I have realised there were one or two local utility classes being used. I have changed this component to use brand context utilities (where they exist) and have inlined one or two others until I can add them to the brand context.

Adds styles

---

toolkits/springernature/packages/springernature-submission-header/HISTORY.md
toolkits/springernature/packages/springernature-submission-header/README.md
toolkits/springernature/packages/springernature-submission-header/package.json
toolkits/springernature/packages/springernature-submission-header/scss/10-settings/spacing.scss
toolkits/springernature/packages/springernature-submission-header/scss/50-components/enhanced.scss
toolkits/springernature/packages/springernature-submission-header/view/header.hbs

This component was originally using a local popup component. This PR incorporates the global-popup component instead.

incorporate popup component

---

context/brand-context/HISTORY.md
context/brand-context/default/scss/10-settings/colors/default.scss
context/brand-context/default/scss/30-mixins/focus.scss
context/brand-context/default/scss/abstracts.scss
context/brand-context/nature/scss/10-settings/colors/default.scss
context/brand-context/nature/scss/40-base/forms.scss
context/brand-context/nature/scss/40-base/layout.scss
context/brand-context/nature/scss/40-base/links.scss
context/brand-context/package.json

Add focus style for tabindex and contenteditable attributes in nature

---

toolkits/springernature/packages/springernature-submission-header/HISTORY.md
toolkits/springernature/packages/springernature-submission-header/README.md
toolkits/springernature/packages/springernature-submission-header/package.json
toolkits/springernature/packages/springernature-submission-header/scss/10-settings/spacing.scss
toolkits/springernature/packages/springernature-submission-header/scss/50-components/enhanced.scss
toolkits/springernature/packages/springernature-submission-header/view/header.hbs

Fixed a typo in the readme.
Tweaked one or two styles for the author details popup.

Sub details header popup 2

---

toolkits/global/packages/global-layout-grid/HISTORY.md
toolkits/global/packages/global-layout-grid/README.md
toolkits/global/packages/global-layout-grid/demo/context.json
toolkits/global/packages/global-layout-grid/demo/dist/index.html
toolkits/global/packages/global-layout-grid/demo/index.hbs
toolkits/global/packages/global-layout-grid/demo/main.scss
toolkits/global/packages/global-layout-grid/package.json
toolkits/global/packages/global-layout-grid/scss/10-settings/default.scss
toolkits/global/packages/global-layout-grid/scss/50-components/layout-grid.scss

In auditing the SPA sites (including springernature.com) I saw a prolific use of grid-like layouts for collections of teasers and other groups of content. These are laid out in various ways, often relying on `@media` queries and sometimes using antiquated grid system dependencies.
This low-level layout component uses CSS Grid progressively to make those approaches obsolete.

Global grid layout

---

toolkits/global/packages/global-author-list/HISTORY.md
toolkits/global/packages/global-author-list/README.md
toolkits/global/packages/global-author-list/demo/context.json
toolkits/global/packages/global-author-list/demo/dist/index.html
toolkits/global/packages/global-author-list/demo/index.hbs
toolkits/global/packages/global-author-list/demo/main.js
toolkits/global/packages/global-author-list/js/__tests__/author-list.spec.js
toolkits/global/packages/global-author-list/js/__tests__/index.spec.js
toolkits/global/packages/global-author-list/js/author-list.js
toolkits/global/packages/global-author-list/js/index.js
toolkits/global/packages/global-author-list/package.json
toolkits/global/packages/global-author-list/scss/50-components/author-list.scss
toolkits/global/packages/global-expander/demo/dist/index.html

- Add JS layer (including tests)
- Update CSS layer
- Update Demo
- Update README

[NM,MC,AK] Add enhanced version of global-author-list

---

toolkits/global/packages/global-layout-grid/HISTORY.md
toolkits/global/packages/global-layout-grid/demo/dist/index.html
toolkits/global/packages/global-layout-grid/package.json
toolkits/global/packages/global-layout-grid/scss/50-components/layout-grid.scss

You can now use `style="--grid--basis: [value]"` for customization.

Grid layout basis (column width) control

---

toolkits/global/packages/global-dropdown/HISTORY.md
toolkits/global/packages/global-dropdown/demo/dist/index.html
toolkits/global/packages/global-dropdown/package.json
toolkits/global/packages/global-dropdown/scss/10-settings/default.scss
toolkits/global/packages/global-dropdown/scss/50-components/dropdown.scss
toolkits/global/packages/global-dropdown/view/dropdown.hbs

Adding ellipsis in the button text
Allow a custom size for the icon will help to adjust the size of the icon independently from the button text

Minor updates dropdown

---

toolkits/global/packages/global-card/HISTORY.md
toolkits/global/packages/global-card/demo/dist/index.html
toolkits/global/packages/global-card/demo/main.scss
toolkits/global/packages/global-card/package.json
toolkits/global/packages/global-card/scss/10-settings/default.scss
toolkits/global/packages/global-card/scss/10-settings/springer.scss
toolkits/global/packages/global-card/scss/50-components/card.scss

* Springer `global-card` settings
* Support for `border` in all cards
* Support for `box-shadow` in all cards

springer card settings

---

toolkits/global/packages/global-lists/HISTORY.md
toolkits/global/packages/global-lists/package.json
toolkits/global/packages/global-lists/scss/10-settings/_nature.scss

add nature override on description list

 Add nature settings file for global-lists

---

toolkits/nature/packages/nature-section-heading/HISTORY.md
toolkits/nature/packages/nature-section-heading/README.md
toolkits/nature/packages/nature-section-heading/package.json

This PR aims to fix the broken images on the Section heading component

Re-add broken images on Section heading

---

toolkits/global/packages/global-details/HISTORY.md
toolkits/global/packages/global-details/demo/dist/index.html
toolkits/global/packages/global-details/package.json
toolkits/global/packages/global-details/scss/10-settings/springer.scss

Springer details branding

---

toolkits/nature/packages/nature-section-heading/HISTORY.md
toolkits/nature/packages/nature-section-heading/README.md
toolkits/nature/packages/nature-section-heading/package.json

This pull request adds better quality images to the nature section heading docs.

Add section heading images

---

toolkits/global/packages/global-card/HISTORY.md
toolkits/global/packages/global-card/demo/context.json
toolkits/global/packages/global-card/demo/dist/index.html
toolkits/global/packages/global-card/demo/index.hbs
toolkits/global/packages/global-card/package.json
toolkits/global/packages/global-card/scss/10-settings/default.scss
toolkits/global/packages/global-card/scss/10-settings/springer.scss
toolkits/global/packages/global-card/scss/10-settings/springernature.scss
toolkits/global/packages/global-card/view/global-card.hbs

```
* Option not to have images
* Removed universal color from default since it is not available universally yet
```

Global card no image

---

toolkits/global/packages/global-pill/HISTORY.md
toolkits/global/packages/global-pill/README.md
toolkits/global/packages/global-pill/package.json
toolkits/global/packages/global-pill/scss/50-components/pill.scss

Allows us to use bordered pills (helps if something is interactive) and borderless pills

Adds borderless modifier to Global Pill

---

toolkits/global/packages/global-details/HISTORY.md
toolkits/global/packages/global-details/package.json
toolkits/global/packages/global-details/scss/10-settings/springer.scss

```
* Spacing tweaks to springer global-details
```

spacing tweaks

---

toolkits/global/packages/global-corporate-footer/HISTORY.md
toolkits/global/packages/global-corporate-footer/README.md
toolkits/global/packages/global-corporate-footer/package.json
toolkits/nature/packages/nature-footer/package.json

This PR updates the footer guidance with information on standard footer links and who to contact with questions.

update footer guidance

---

toolkits/global/packages/global-corporate-footer/HISTORY.md
toolkits/global/packages/global-corporate-footer/README.md
toolkits/global/packages/global-corporate-footer/package.json

This PR updates footer guidance with post-review changes from @leonasiu. Specifically:
- update contact details for accessibility specialists
- update guidance on terms and conditions links

Subject matter expert footer amends

---

toolkits/global/packages/global-autocomplete/HISTORY.md
toolkits/global/packages/global-autocomplete/__tests__/index.js
toolkits/global/packages/global-autocomplete/demo/dist/index.html
toolkits/global/packages/global-autocomplete/demo/main.js
toolkits/global/packages/global-autocomplete/js/index.js
toolkits/global/packages/global-autocomplete/package.json

* BREAKING: Bump brand-context from version 4.2.2 to 20.1.1 (Moved from node sass to dart sass)
* Option to select list item with tab
* Add aria-expanded on initialisation
* Updated demo
* Regenerated to demo latest changes
* Add selected item to text input when selectOnSuggestionBrowsing is false otherwise looks like it nothing selected

Option to select autosuggest items with tab

---

toolkits/global/packages/global-card/HISTORY.md
toolkits/global/packages/global-card/demo/context.json
toolkits/global/packages/global-card/demo/dist/index.html
toolkits/global/packages/global-card/demo/index.hbs
toolkits/global/packages/global-card/package.json
toolkits/global/packages/global-card/scss/10-settings/springer.scss
toolkits/global/packages/global-card/scss/50-components/card.scss
toolkits/global/packages/global-card/view/global-card.hbs
toolkits/springer/packages/springer-hero/HISTORY.md
toolkits/springer/packages/springer-hero/demo/dist/index.html
toolkits/springer/packages/springer-hero/package.json
toolkits/springer/packages/springer-hero/scss/50-components/springer-hero.scss

```
* Title optional
* White background-color for springer
* Body padding removed where no image
```
```
* Image sized to content (and automatically is removed from narrow view)
```

Card and hero tweaks

---

context/brand-context/HISTORY.md
context/brand-context/package.json
context/brand-context/springernature/scss/10-settings/typography.scss

Updates the h3 and h5 line height for Springer Nature

Update line height

---

toolkits/nature/packages/nature-footer/HISTORY.md
toolkits/nature/packages/nature-footer/demo/context.json
toolkits/nature/packages/nature-footer/demo/dist/index.html
toolkits/nature/packages/nature-footer/package.json
toolkits/nature/packages/nature-footer/scss/10-settings/footer.scss
toolkits/nature/packages/nature-footer/scss/50-components/footer.scss
toolkits/nature/packages/nature-footer/view/footer.hbs

BREAKING:
* Removes dependency on utility classnames
* Removes dependency on Media component
* Bumps Brand Context dependency to version 22.0.0

Updates Nature Footer with improvements

---

toolkits/springernature/packages/springernature-user-details/HISTORY.md
toolkits/springernature/packages/springernature-user-details/package.json
toolkits/springernature/packages/springernature-user-details/scss/50-components/core.scss
toolkits/springernature/packages/springernature-user-details/scss/50-components/enhanced.scss

Fix font size and colour issue

---

toolkits/springer/packages/springer-hero/HISTORY.md
toolkits/springer/packages/springer-hero/README.md
toolkits/springer/packages/springer-hero/demo/context.json
toolkits/springer/packages/springer-hero/demo/dist/index.html
toolkits/springer/packages/springer-hero/demo/index.hbs
toolkits/springer/packages/springer-hero/package.json
toolkits/springer/packages/springer-hero/scss/10-settings/springer-hero.scss
toolkits/springer/packages/springer-hero/scss/50-components/springer-hero.scss
toolkits/springer/packages/springer-hero/view/springer-hero.hbs

```
* BREAKING:
* Further simplification of API
* Normalization of content spacing
* `smallerImage` mode
```

Springer Hero - Version 3: simplification, spacing, smaller images

---

toolkits/springer/packages/springer-listing/HISTORY.md
toolkits/springer/packages/springer-listing/README.md
toolkits/springer/packages/springer-listing/demo/context.json
toolkits/springer/packages/springer-listing/demo/dist/index.html
toolkits/springer/packages/springer-listing/demo/index.hbs
toolkits/springer/packages/springer-listing/package.json
toolkits/springer/packages/springer-listing/scss/50-components/_listing.scss
toolkits/springer/packages/springer-listing/view/springer-listing.hbs

```
* BREAKING:
* line-clamping now _opt in_
* Debug removed
```

Opt in to line truncation and debug removal

---

toolkits/global/packages/global-details/HISTORY.md
toolkits/global/packages/global-details/demo/dist/index.html
toolkits/global/packages/global-details/package.json
toolkits/global/packages/global-details/view/details.hbs

```
* Remove redundant utility class
```

remove redundant problematic util class

---

toolkits/global/packages/global-card/demo/dist/index.html
toolkits/springer/packages/springer-publisher-footer/HISTORY.md
toolkits/springer/packages/springer-publisher-footer/package.json
toolkits/springer/packages/springer-publisher-footer/scss/10-settings/_publisher-footer.scss

This is to compensate for the legal stuff going in the corporate footer.

from 5 to 4 columns

---

toolkits/springer/packages/springer-header/HISTORY.md
toolkits/springer/packages/springer-header/package.json
toolkits/springer/packages/springer-header/scss/50-components/_header.scss
toolkits/springer/packages/springer-header/view/springer-header.hbs

```
* Support different imprint logos and their dimensions
```

Apply auto logo width

---

context/brand-context/HISTORY.md
context/brand-context/package.json
context/brand-context/springer/scss/30-mixins/typography.scss
context/brand-context/springer/scss/40-base/basic.scss
context/brand-context/springer/scss/40-base/typography.scss
toolkits/springer/packages/springer-header/HISTORY.md
toolkits/springer/packages/springer-header/demo/dist/index.html
toolkits/springer/packages/springer-header/package.json
toolkits/springer/packages/springer-header/scss/50-components/_header.scss

```
* Match different logo heights
```

Springer logo constrained height

---

toolkits/global/packages/global-status-message/HISTORY.md
toolkits/global/packages/global-status-message/package.json
toolkits/global/packages/global-status-message/scss/10-settings/default.scss

```
* even icon spacing for longform content
```

global-status-message spacing adjustment

---

context/brand-context/HISTORY.md
context/brand-context/default/scss/00-tokens/_background.variables.scss
context/brand-context/default/scss/00-tokens/_border.variables.scss
context/brand-context/default/scss/00-tokens/_breakpoints.variables.scss
context/brand-context/default/scss/00-tokens/_button.variables.scss
context/brand-context/default/scss/00-tokens/_color.variables.scss
context/brand-context/default/scss/00-tokens/_font-weight.variables.scss
context/brand-context/default/scss/00-tokens/_icon.variables.scss
context/brand-context/default/scss/00-tokens/_link.variables.scss
context/brand-context/default/scss/00-tokens/_sizing.variables.scss
context/brand-context/default/scss/00-tokens/_spacing.variables.scss
context/brand-context/default/scss/00-tokens/_state.variables.scss
context/brand-context/default/scss/00-tokens/_text.variables.scss
context/brand-context/default/scss/00-tokens/_typography.variables.scss
context/brand-context/default/scss/00-tokens/_ui.variables.scss
context/brand-context/nature/scss/00-tokens/_illustration.variables.scss
context/brand-context/nature/scss/00-tokens/_typography.variables.scss
context/brand-context/package.json
context/brand-context/springer/scss/00-tokens/_typography.variables.scss
context/brand-context/springernature/scss/00-tokens/_breakpoints.variables.scss
context/brand-context/springernature/scss/00-tokens/_typography.variables.scss
context/design-tokens/alias/default/border/border.json
context/design-tokens/components/global/global-forms/default.json
toolkits/global/packages/global-forms/package.json

Following discussion with James A in the Elements team. These changes need to be made.

Updates border alias tokens and Pictographic Radio component tokens

---

toolkits/global/packages/global-ratings-survey/HISTORY.md
toolkits/global/packages/global-ratings-survey/__tests__/ratings-survey.js
toolkits/global/packages/global-ratings-survey/demo/dist/index.html
toolkits/global/packages/global-ratings-survey/js/ratings-survey.js
toolkits/global/packages/global-ratings-survey/package.json
toolkits/global/packages/global-ratings-survey/view/ratingsSurvey.hbs

Adds a method to the Global Ratings Survey class to allow us to append the user's window.location.href to Survey Monkey links as a custom variable

Add referrer to global ratings survey

---

context/brand-context/HISTORY.md
context/brand-context/default/scss/00-tokens/_typography.variables.scss
context/brand-context/default/scss/40-base/block-spacing.scss
context/brand-context/package.json
context/design-tokens/alias/default/typography/typography.json

at some point block spacing tokens got moved around in the json and were no longer being compiled.
This fixes that.

fixes a naming issue and missing value issue

---

toolkits/global/packages/global-forms/HISTORY.md
toolkits/global/packages/global-forms/README.md
toolkits/global/packages/global-forms/package.json

Change h2s to h3s in Checkboxes docs

---

toolkits/nature/packages/nature-hero/README.md

Updated documentation to follow new component documentation pattern.

Update to documentation

---

toolkits/global/packages/global-status-message/README.md

Updated documentation to follow new pattern, removed broken screenshots.

Improvements to documentation

---

toolkits/global/packages/global-status-message/HISTORY.md
toolkits/global/packages/global-status-message/package.json
toolkits/nature/packages/nature-hero/HISTORY.md
toolkits/nature/packages/nature-hero/package.json

This pr only updates the version and the history, because the changes to the readme are already made and committed to main branch by another team member

update components version and history

---

toolkits/global/packages/global-skip-link/HISTORY.md
toolkits/global/packages/global-skip-link/package.json

Publish new version for change of documentation.
See https://github.com/springernature/frontend-toolkits/pull/874/files

Update and improve global-skip-link component documentation

---

toolkits/global/packages/global-corporate-footer/HISTORY.md
toolkits/global/packages/global-corporate-footer/README.md
toolkits/global/packages/global-corporate-footer/demo/context.json
toolkits/global/packages/global-corporate-footer/demo/dist/index.html
toolkits/global/packages/global-corporate-footer/package.json
toolkits/global/packages/global-footer/HISTORY.md
toolkits/global/packages/global-footer/README.md
toolkits/global/packages/global-footer/demo/context.json
toolkits/global/packages/global-footer/demo/dist/index.html
toolkits/global/packages/global-footer/package.json

Update footer text content https://github.com/springernature/ux-elements-docs/issues/134

change text content for footer - #134

---

toolkits/global/packages/global-details/HISTORY.md
toolkits/global/packages/global-details/package.json
toolkits/global/packages/global-details/scss/10-settings/springer.scss

This component used a block spacing variable that no longer exists in the latest version of Brand Context

Updates Global Details component after Brand Context update that removed block spacing

---

toolkits/global/packages/global-customer-satisfaction-input/HISTORY.md
toolkits/global/packages/global-customer-satisfaction-input/demo/dist/index.html
toolkits/global/packages/global-customer-satisfaction-input/package.json
toolkits/global/packages/global-customer-satisfaction-input/view/customerSatisfactionInput.hbs

* Fixes issue with SVG not rendering correctly in Firefox. Ids used in HTML have been refactored and properly namespaced.

Version 1.0.2 Global Customer Satisfaction Input component

---

toolkits/global/packages/global-loader-animation/HISTORY.md
toolkits/global/packages/global-loader-animation/package.json

Bump version
