springernature/frontend-toolkits

- toolkits/nature/packages/nature-context/HISTORY.md
- toolkits/nature/packages/nature-context/package.json
- toolkits/nature/packages/nature-context/scss/10-settings/typography-nature.scss
Removing variable `font-family-sans` from nature-context as we will now get it from `global-context/scss/10-settings/typography.scss`
> Remove font-family-sans

- toolkits/nature/packages/nature-context/HISTORY.md
- toolkits/nature/packages/nature-context/package.json
Last published version did not extend properly and only published the nature files _without_ the global files. Hopefully, by re-pushing this with a bug fix it should publish correctly.
> nature-context v0.18.1

- toolkits/springer/packages/springer-author-list/HISTORY.md
- toolkits/springer/packages/springer-author-list/package.json
- toolkits/springer/packages/springer-box/HISTORY.md
- toolkits/springer/packages/springer-box/package.json
- toolkits/springer/packages/springer-lists/HISTORY.md
- toolkits/springer/packages/springer-lists/package.json
- updated in springer-author-list, springer-box, springer-lists
- updated major version of each package
- some formatting change to be consistent
> Bumps peer dependency springer-context to 12.2.2 on outdated packages

- toolkits/springer/packages/springer-author-list/HISTORY.md
- toolkits/springer/packages/springer-author-list/package.json
- toolkits/springer/packages/springer-box/HISTORY.md
- toolkits/springer/packages/springer-box/package.json
- toolkits/springer/packages/springer-context/HISTORY.md
- toolkits/springer/packages/springer-context/package.json
- toolkits/springer/packages/springer-lists/HISTORY.md
- toolkits/springer/packages/springer-lists/package.json
also bumps peer dependency springer-context to 12.3.0 in several packages
> Bumps global-context extends version to 9.2.0 in springer-context

- toolkits/springer/packages/springer-card/HISTORY.md
- toolkits/springer/packages/springer-card/package.json
`springer-card` already existed in repo but appears unused. Bumping to next major version from version 1.0.0 to take over.
> bump springer-card to 2.0.0

- toolkits/global/packages/global-article/HISTORY.md
- toolkits/global/packages/global-article/js/authors.js
- toolkits/global/packages/global-article/js/disqus.js
- toolkits/global/packages/global-article/js/popup.js
- toolkits/global/packages/global-article/js/reading-companion.js
- toolkits/global/packages/global-article/package.json
Some changes made to `global-article` based on new linting rules broke the JS in IE10.
This PR reverts the use of `append`, `includes`, and `remove` and instead disables the linting rules for those lines.
> global-article: revert linting changes that break IE10

- toolkits/global/packages/global-context/HISTORY.md
- toolkits/global/packages/global-context/package.json
- toolkits/global/packages/global-context/scss/60-utilities/colors.scss
- toolkits/springer/packages/springer-context/HISTORY.md
- toolkits/springer/packages/springer-context/package.json
- toolkits/springer/packages/springer-context/scss/60-utilities/colors.scss
- toolkits/springer/packages/springer-context/scss/60-utilities/springer-colors.scss
- toolkits/springer/packages/springer-context/scss/60-utilities/springer-float.scss
`color.scss` in global-context got overriden because `color.scss` was added for springer-context. Renamed to springer-color to avoid clashing with global version.
Make color utility class name consistent and removed springer-floats (unused in sites-springer).
> Fix open access color

- toolkits/nature/packages/nature-article/README.md
- toolkits/springernature/packages/springer-nature-modal/HISTORY.md
- toolkits/springernature/packages/springer-nature-modal/README.md
- toolkits/springernature/packages/springer-nature-modal/__tests__/unit/modal.spec.js
- toolkits/springernature/packages/springer-nature-modal/js/modal.js
- toolkits/springernature/packages/springer-nature-modal/package.json
- toolkits/springernature/packages/springer-nature-modal/scss/50-components/springer-nature-modal.scss
Display a modal (pop-up) window
```html
<button data-modal-for="example-modal">Click this button to open the modal</button>
<div data-component-modal id="example-modal" class="c-modal js-hide" tabindex="0">
<div class="c-modal--content">
<h4 class="c-modal--title u-mb20">Modal Title</h4>
<div class="c-modal--body">
<p>This is the modal! It has a <a data-component-modal-close class="close-modal-link btn-close" href="">link</a> that can also close it.</p>
</div>
<button data-component="modal-close" class="c-modal--close btn-close link-like">&times;</button>
</div>
</div>
```
```javascript
import Modal from '@springernature/springer-nature-modal';
const modalElement = document.querySelector('#example-modal'); //For multiple modals, prefer …
```
> Adds springer-nature-modal

- toolkits/global/packages/global-context/HISTORY.md
- toolkits/global/packages/global-context/package.json
- toolkits/global/packages/global-context/scss/30-mixins/links.scss
- toolkits/global/packages/global-context/scss/60-utilities/links.scss
- Renames u-x-link to u-link-x for consistency with other utilities
- Adds u-link-inherit and u-link-underline
> global-context: breaking - renames link utility / adds link utilities

- toolkits/nature/packages/nature-context/HISTORY.md
- toolkits/nature/packages/nature-context/package.json
- toolkits/nature/packages/nature-context/scss/enhanced.scss
- toolkits/springer/packages/springer-context/HISTORY.md
- toolkits/springer/packages/springer-context/package.json
- toolkits/springer/packages/springer-context/scss/30-mixins/springer-links.scss
Note: breaking change in Springer because of the use of majors already. In Nature, there's never been a major release so breaking changes can be included in the minor (until v1 is released).
Springer already imported links from global.
> nature/springer context: update to latest global context

- toolkits/global/packages/global-context/HISTORY.md
- toolkits/global/packages/global-context/package.json
- toolkits/global/packages/global-context/scss/10-settings/typography.scss
so we can remove the overrides from the brand level, they all use 1.8em as there base size. If any want to vary in the future they can add this back at a brand level.
> Increase the base font size

- toolkits/nature/packages/nature-context/HISTORY.md
- toolkits/nature/packages/nature-context/package.json
- toolkits/nature/packages/nature-context/scss/10-settings/typography-nature.scss
and bump the global-context version on extends-package, so we get the base font size from that.
> Remove base font size

- toolkits/global/packages/global-banner/HISTORY.md
- toolkits/global/packages/global-banner/package.json
- toolkits/global/packages/global-banner/scss/50-components/_banner.scss
Banner links should always have underlines, regardless of the brand.
This is because the banner is intended to be a combination of a text and links (normally in a sentence).
Bumps global-context peer dep.
> global-banner: sets underline on links

- toolkits/global/packages/global-context/HISTORY.md
- toolkits/global/packages/global-context/package.json
- toolkits/global/packages/global-context/scss/60-utilities/display.scss
- toolkits/global/packages/global-context/scss/60-utilities/flex.scss
I'm making these consistent for now.
Whether this is the approach in the long term is still up for debate.
> global-context: breaking - flex utility names

- toolkits/nature/packages/nature-context/HISTORY.md
- toolkits/nature/packages/nature-context/package.json
- toolkits/nature/packages/nature-context/scss/10-settings/typography-nature.scss
- toolkits/nature/packages/nature-context/scss/30-mixins/typography-nature.scss
- toolkits/nature/packages/nature-context/scss/40-base/typography-nature.scss
- toolkits/nature/packages/nature-context/scss/60-utilities/typography-nature.scss
Heading styles applied via mixins.
`h4` is the final level. `h5` and `h6` are presentationally the same as `h4`.
Note: I could find anything that uses the `h5` tag in the html for Nature so it felt safe to remove.
> nature-context: nature headings

- toolkits/global/packages/global-forms/HISTORY.md
- toolkits/global/packages/global-forms/package.json
- toolkits/global/packages/global-forms/scss/50-components/_global-forms.scss
Input row items were set to have the ability to grow but not shrink `flex: 1 0 auto`. This meant that on small screens the input boxes would exceed the width of the page. This updates row items to be able to shrink as well as grow `flex: 1 1 auto`.
> Allow input rows to shrink as well as grow

- toolkits/global/packages/global-expander/HISTORY.md
- toolkits/global/packages/global-expander/__tests__/expander.spec.js
- toolkits/global/packages/global-expander/js/expander.js
- toolkits/global/packages/global-expander/package.json
* Bug Fix: this._tabbableItems is null
* Bug Fix: Set focus back on trigger after tabbing out of the target
* Adds tests for keyboard interactions
> global-expander: Keyboard interaction fixes

- toolkits/global/packages/global-context/HISTORY.md
- toolkits/global/packages/global-context/package.json
- toolkits/global/packages/global-context/scss/10-settings/colors/shared.scss
There was insufficient contrast against `#FCFCFC` background.
> Update open access color to improve contrast

- toolkits/nature/packages/nature-context/HISTORY.md
- toolkits/nature/packages/nature-context/package.json
- toolkits/nature/packages/nature-context/scss/10-settings/typography-nature.scss
- toolkits/nature/packages/nature-context/scss/30-mixins/typography-nature.scss
For _reasons_ the margins need to be much smaller for headings.
Sizes for smaller headings are bumped a bit.
> nature-context: Changes to nature headings

- toolkits/global/packages/global-article/HISTORY.md
- toolkits/global/packages/global-article/__tests__/reading-companion.js
- toolkits/global/packages/global-article/js/reading-companion.js
- toolkits/global/packages/global-article/package.json
The changes on the reading-companion.js correspond mostly to indentation and other bits related to transforming the component in an IIFE function that returns another function. 
And lately, getting the component to export.
There is one test that can be added still. But for now, the tests cover 90% of the code.
> convert reading companion to use module.exports and add tests and export

- toolkits/global/packages/global-button/HISTORY.md
- toolkits/global/packages/global-button/README.md
- toolkits/global/packages/global-button/package.json
- toolkits/global/packages/global-button/scss/10-settings/button.scss
- toolkits/global/packages/global-button/scss/30-mixins/button.scss
- toolkits/global/packages/global-button/scss/50-components/button.scss
* BREAKING: Rename .c-button--block to .c-button--full-width
* BREAKING: Replace text-align with justify-content and variable rename
* Replace inline-block with inline-flex
* Add SVG spacing to buttons with .c-button-icon--left and .c-button-icon--right
* Move border-radius from base to themes
* Update readme
> add icon spacing to global-button

- toolkits/global/packages/global-article/HISTORY.md
- toolkits/global/packages/global-article/package.json
- toolkits/global/packages/global-article/scss/10-settings/article.scss
- toolkits/global/packages/global-article/scss/50-components/article-enhanced.scss
- toolkits/global/packages/global-article/scss/50-components/article-metrics.scss
Making the article use the new global breakpoints so we can get consistency across the pages. Removes the need for article specific breakpoints hence the removal of $article--breakpoints
> Update breakpoints to use global

- toolkits/springer/packages/springer-button/HISTORY.md
- toolkits/springer/packages/springer-button/package.json
- toolkits/springer/packages/springer-button/scss/10-settings/button-springer.scss
* Fixed typo in $button--padding-large
* Changes to be compatible with global-button@0.2.0
* Replace variable from $button--text-align to $button--justify-content
* Move border-radius from base to themes
* Bump extendsPackage to latest
> Springer-button version bump

- toolkits/springer/packages/springer-context/HISTORY.md
- toolkits/springer/packages/springer-context/package.json
- toolkits/springer/packages/springer-context/scss/10-settings/colors/default.scss
- toolkits/springer/packages/springer-context/scss/30-mixins/headings.scss
* Change visited color
* Remove element state colors from heading-link mixin to maintain consistency with regular links
> update visited colors in springer-toolkit

- toolkits/springer/packages/springer-article/HISTORY.md
- toolkits/springer/packages/springer-article/package.json
So that we can get the latest global article which use the most up to date breakpoints and naming.
> Bumps the global article version number

- toolkits/global/packages/global-autocomplete/HISTORY.md
- toolkits/global/packages/global-autocomplete/js/index.js
- toolkits/global/packages/global-autocomplete/package.json
Internet Explorer uses non-standard key identifiers, so this change allows for 'Down' in place of 'ArrrowDown' and 'Up' in place of 'ArrowUp'.
> Allow for explorers lovely non-standard key identifiers

- toolkits/global/packages/global-javascript/HISTORY.md
- toolkits/global/packages/global-javascript/README.md
- toolkits/global/packages/global-javascript/__tests__/unit/dom/get-data-options.spec.js
- toolkits/global/packages/global-javascript/__tests__/unit/util/make-array.spec.js
- toolkits/global/packages/global-javascript/js/helpers/dom/get-data-options.js
- toolkits/global/packages/global-javascript/js/helpers/index.js
- toolkits/global/packages/global-javascript/js/helpers/util/make-array.js
- toolkits/global/packages/global-javascript/package.json
Move javascript helpers out of `global-context` into its own package. No new code here, just publishing as a separate package
> global-javascript

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/abstracts.scss
- context/brand-context/package.json
BUG:
`30-mixins/links.scss` is missing from `abstracts.scss` in default
> links mixin missing from default context brand

- context/brand-context/default/scss/60-utilities/hiding.scss
Adding `.u-hide-print` to the brand context (as advised by @davidpauljunior ) so that the Briefing banner can use it.
> [CM] Add print hiding utility class to brand context

- package-lock.json
- package.json
- toolkits/springer/packages/springer-dropdown/HISTORY.md
- toolkits/springer/packages/springer-dropdown/package.json
This should regenerate the `post-install` command so that a version is explicitly requested via `npx` from the latest version of the package manager.
> Bump springer dropdown

- context/brand-context/HISTORY.md
- context/brand-context/package.json
- context/brand-context/springer/scss/10-settings/typography.scss
- context/brand-context/springer/scss/30-mixins/headings.scss
- context/brand-context/springer/scss/60-utilities/typography.scss
* All headings to use $line-height-tight
* All headings to have 1em margin bottom
* All headings to stop using rfs mixin
* h1: 28px => 32px
* h2: 26px => 28px
* h4: serif => sans-serif
**Old**
**New**
> Update Springer Heading Typography

- context/brand-context/HISTORY.md
- context/brand-context/package.json
- context/brand-context/springer/scss/30-mixins/headings.scss
Native CSS variables and SCSS variables clash, causing a compilation error.
> Springer headings variable compilation fix

- context/brand-context/HISTORY.md
- context/brand-context/default/README.md
- context/brand-context/default/scss/10-settings/buttons.scss
- context/brand-context/default/scss/30-mixins/buttons.scss
- context/brand-context/default/scss/30-mixins/style.scss
- context/brand-context/default/scss/60-utilities/buttons.scss
- context/brand-context/default/scss/60-utilities/style.scss
- context/brand-context/default/scss/abstracts.scss
- context/brand-context/nature/scss/10-settings/buttons.scss
- context/brand-context/nature/scss/abstracts.scss
- context/brand-context/package.json
- context/brand-context/springer/scss/10-settings/buttons.scss
- context/brand-context/springer/scss/abstracts.scss
Button styling is fairly "low level" and we have a few instances of components that need to use button styles, but we want to avoid cross-component dependencies.
This PR moves the code from `global-button` into the `brand-context` so that button styles are available to any component.
This involves a breaking change that moves the `u-button-reset` utility out of the `buttons.scss` file and into `style.scss` to make it more obvious that this does not relate to branded buttons, but rather the `<button>` element.
> Add button styles to the `brand-context`

- toolkits/global/packages/global-ad/HISTORY.md
- toolkits/global/packages/global-ad/README.md
- toolkits/global/packages/global-ad/package.json
- toolkits/global/packages/global-ad/scss/10-settings/default.scss
- toolkits/global/packages/global-ad/scss/50-components/ad.scss
- Move font styles to `.c-ad__label`
- Update readme examples
- Bump `brand-context` version
> increase specificity on font styles for global-ad

- toolkits/global/packages/global-javascript/HISTORY.md
- toolkits/global/packages/global-javascript/README.md
- toolkits/global/packages/global-javascript/__tests__/unit/util/create-event.spec.js
- toolkits/global/packages/global-javascript/package.json
- toolkits/global/packages/global-javascript/src/helpers/index.js
- toolkits/global/packages/global-javascript/src/helpers/util/create-event.js
Creates a wrapper around `customEvent` that allows components to communicate with each other safely using namespaced events.
```javascript
const elementToBind = document.getElementById('element');
// Create event namespaced to component
const event = createEvent('eventName', 'componentName', {
bubbles:true,
cancelable: true,
detail: {
hazcheeseburger: true
}
});
// Dispatch event
elementToBind.dispatchEvent(event);
// Listen for event
elementToBind.addEventListener('componentName:eventName', function (event) {
// Do something
}, false);
```
> createEvent helper

- toolkits/global/packages/global-expander/HISTORY.md
- toolkits/global/packages/global-expander/README.md
- toolkits/global/packages/global-expander/__tests__/expander.spec.js
- toolkits/global/packages/global-expander/__tests__/index.spec.js
- toolkits/global/packages/global-expander/js/expander.js
- toolkits/global/packages/global-expander/js/index.js
- toolkits/global/packages/global-expander/package.json
Following on from https://github.com/springernature/frontend-toolkits/pull/289
When using global expander in another component there are times where you need to do something before global expander focuses on the target element. This custom event allows the consumer of global expander to set an event listener and react accordingly.
> Adds focus event to global expander

- toolkits/global/packages/global-expander/HISTORY.md
- toolkits/global/packages/global-expander/README.md
- toolkits/global/packages/global-expander/js/expander.js
Whether it was intentional or not I'm unsure but it already was the case that you can call `expander._close()` and `expander._open()` but this makes it more obvious when reading the code.
Also note that it is needed to expose these methods. For example if you have a close button on a popup that uses global-expander. That close button needs a way to close the popup, the best way being to manually call something like `expander.close()` (because you need to update expander instance's `isOpen` state)
> Makes it clear that open and close method are public

- toolkits/global/packages/global-expander/HISTORY.md
- toolkits/global/packages/global-expander/__tests__/expander.spec.js
- toolkits/global/packages/global-expander/js/expander.js
- toolkits/global/packages/global-expander/package.json
Fixes focus being lost from expander when there is no other tabbable item after it on the page.
> Detect last tabbable item on tab out to set focus on trigger

- toolkits/global/packages/global-popup/HISTORY.md
- toolkits/global/packages/global-popup/README.md
- toolkits/global/packages/global-popup/__tests__/popup.spec.js
- toolkits/global/packages/global-popup/js/popup.js
- toolkits/global/packages/global-popup/package.json
The hook option was causing issues on mobile so needed a rethink. It's better to always position a popup relative to the body. It makes `width: auto` easier to think about as well as any `MAX_WIDTH` option that may have been set.
> Removes hook option from global-popup

- toolkits/global/packages/global-popup/HISTORY.md
- toolkits/global/packages/global-popup/package.json
- toolkits/global/packages/global-popup/scss/10-settings/_global-popup.scss
I attempted to fix this yesterday but it didn't work. This just hardcodes the colour which I think is fine. The colour looks good on both Nature and Springer products. And if anyone wants to override they can simply with a 10-settings scss file in the app.
> A better fix for global popup border colours not being found

- toolkits/global/packages/global-corporate-footer/HISTORY.md
- toolkits/global/packages/global-corporate-footer/package.json
- toolkits/global/packages/global-corporate-footer/scss/10-settings/nature.scss
- toolkits/global/packages/global-corporate-footer/scss/50-components/corporate-footer.scss
- Use font-size mixin
- Use pixel value for nature font-size to workaround clash of mixin
> use font-size mixin in global-corporate-footer

- context/brand-context/HISTORY.md
- context/brand-context/package.json
- context/brand-context/springernature/scss/30-mixins/typography.scss
There are still some references to the `global-spacing` function, which does not exist and seems to have been replaced by `spacing` in the Default branding context. This PR changes the function reference and alters sizing to permitted values.
> Fix references to global-spacing in typography.scss

- context/brand-context/HISTORY.md
- context/brand-context/package.json
- context/brand-context/springer/scss/30-mixins/hiding.scss
on springer "skip link" is not visible the cause are: 
- `position: absolute !important;` in `.u-visually-hidden` overrides `position: static`  
-  `margin: -100%;` from  `.u-visually-hidden` is not reset
I took this approach because not sure if I can remove `!important` from `.u-visually-hidden`
> fix visually hidden on focus mixin

- toolkits/global/packages/global-meta/HISTORY.md
- toolkits/global/packages/global-meta/README.md
- toolkits/global/packages/global-meta/package.json
- toolkits/global/packages/global-meta/scss/10-settings/_default.scss
- toolkits/global/packages/global-meta/scss/10-settings/_springer.scss
- toolkits/global/packages/global-meta/scss/50-components/_meta.scss
The Springer nature brand is going to be using the `springer-meta` component, so the first stage is to create a `global-meta` component, copy the code across and create branded entrypoints for `default` and `springer`. Later we will add the springernature brand.
Once all products are moved from `springer-meta` to `global-meta`, we will delete the `springer-meta` code and deprecate the package on NPM.
> Add global-meta package

- toolkits/nature/packages/nature-header/HISTORY.md
- toolkits/nature/packages/nature-header/package.json
- toolkits/nature/packages/nature-header/scss/50-components/header.scss
* Maintain logo alignment when scaling SVG
* Bump global-expander to 2.1.0
> fix logo alignment in nature header

- toolkits/global/packages/global-autocomplete/HISTORY.md
- toolkits/global/packages/global-autocomplete/README.md
- toolkits/global/packages/global-autocomplete/package.json
Unescaped code in `README.md` meant that we were trying to render that HTML on the styleguide, instead of chowing the code.
> Autocomplete readme

- toolkits/global/packages/global-expander/HISTORY.md
- toolkits/global/packages/global-expander/README.md
- toolkits/global/packages/global-expander/__tests__/expander.spec.js
- toolkits/global/packages/global-expander/__tests__/index.spec.js
- toolkits/global/packages/global-expander/js/expander.js
- toolkits/global/packages/global-expander/js/index.js
- toolkits/global/packages/global-expander/package.json
At the moment Oscar repo is the only consumer of Global Expander that uses the FOCUS_EVENT option. We have a bug on Oscar at the moment which has led me to the realisation that we do not need Global Expander to focus on an element once it has done its thing. But there is still a requirement to know when Global Expander has finished opening a toggle-able element, therefore an event dispatched by Global Expander is still needed.
Therefore this PR changes the event to be what Oscar needs. Plus, it is likely to be a more useful event to any other consumer of the component. As the option now means that it is sending an event when it opens a toggle-able element, rather than an event specifically concerned with when it focused on a target element during the open process.
Relates to PR …
> Changes Global Expander's FOCUS_EVENT option to OPEN_EVENT

- toolkits/global/packages/global-popup/HISTORY.md
- toolkits/global/packages/global-popup/__tests__/popup.spec.js
- toolkits/global/packages/global-popup/js/popup.js
- toolkits/global/packages/global-popup/package.json
A recent bug led me to the realisation that it is problematic if Global Expander focuses on a Popup when it opens. A popup has not finished rendering when we try and calculate its height when Global Expander opens and focuses the popup element. This results in incorrect height calculations and subsequent broken positioning of the popup element.
Therefore it's better to not ask Global Expander to focus on the popup. Instead Global Popup focuses on the popup itself but only once Global Expander has fired an event to announce that it has finished opening the popup.
Relates to PR https://github.com/springernature/frontend-toolkits/pull/360
> Global Popup now focuses on the Popup itself and stops using some of Global Expander's options

- toolkits/global/packages/global-forms/HISTORY.md
- toolkits/global/packages/global-forms/README.md
- toolkits/global/packages/global-forms/package.json
- toolkits/global/packages/global-forms/scss/10-settings/_default.scss
- toolkits/global/packages/global-forms/scss/50-components/_forms.scss
Fix mixin name in component file as the build was complaining it could not find `global-form-input` mixin which got renamed to `form-input`.
> fix mixin name in global-form 

- toolkits/springernature/packages/springernature-header/HISTORY.md
- toolkits/springernature/packages/springernature-header/package.json
- toolkits/springernature/packages/springernature-header/scss/50-components/enhanced.scss
Use auto sizes for logo image, as explorer doesn't maintain ratio
> fix for explorer image sizing

- context/brand-context/HISTORY.md
- context/brand-context/nature/scss/10-settings/typography.scss
- context/brand-context/nature/scss/30-mixins/typography.scss
- context/brand-context/package.json
Also brings back the `font-family-serif` variable override
> Nature Context: Makes variable names more consistent

- toolkits/global/packages/global-breadcrumbs/HISTORY.md
- toolkits/global/packages/global-breadcrumbs/package.json
- toolkits/global/packages/global-breadcrumbs/scss/10-settings/default.scss
- toolkits/global/packages/global-breadcrumbs/scss/50-components/breadcrumbs.scss
Chevrons got misaligned after swapping out c-icon(refactor-pandora) for u-icon(brand-context)
> reposition chevron on global-breadcrumbs

- toolkits/global/packages/global-javascript/HISTORY.md
- toolkits/global/packages/global-javascript/__tests__/unit/dom/get-data-options.spec.js
- toolkits/global/packages/global-javascript/package.json
- toolkits/global/packages/global-javascript/src/helpers/dom/get-data-options.js
Previously they were set in the object as strings, meaning that `"false"` options would be evaluated to true.
> global-javascript getDataOptions: Convert "true" and "false" attributes to boolean

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/30-mixins/hiding.scss
- context/brand-context/default/scss/60-utilities/hiding.scss
- context/brand-context/package.json
- context/brand-context/springer/scss/30-mixins/hiding.scss
Had an issue today where our u-hide utility classnames were not working because of selector specificity, i.e. we had some css that set display: block and because of the specificity of it it trumped the hide utility. I think it makes sense to add important to hide utilities in general. If we've made the conscious choice to add a classname like u-hide to the html then it should be a certainty that the element is hidden.
> Adds important to hide utilities

- toolkits/nature/packages/nature-header/HISTORY.md
- toolkits/nature/packages/nature-header/package.json
- toolkits/nature/packages/nature-header/scss/50-components/header.scss
The logo can be an `h1`, for example on journal homepages.
> nature-header: Zeros line-height to allow use of h1

- toolkits/nature/packages/nature-header/HISTORY.md
- toolkits/nature/packages/nature-header/package.json
- toolkits/nature/packages/nature-header/scss/50-components/header.scss
https://jira.springernature.com/browse/PAN-1053
`Explore content` turns to `Content` at narrow widths in header so needed to capitalize link when `Explore` is hidden.
> Capitalize links in nature header

- toolkits/global/packages/global-lists/HISTORY.md
- toolkits/global/packages/global-lists/package.json
- toolkits/global/packages/global-lists/scss/10-settings/_default.scss
- toolkits/global/packages/global-lists/scss/10-settings/_springer.scss
- toolkits/global/packages/global-lists/scss/50-components/_list-description.scss
- toolkits/global/packages/global-lists/scss/50-components/_list-group.scss
The component uses a mixin for `interface-link` which is only available from the Springer brand of the `brand-context`.
This PR uses conditional variables to make sure that this mixin is only used for the Springer branded version of the global component.
In the future, we are going to add the `interface-link` concept to the default `brand-context` so that it is available to all, and release a new version of this component.
> BUG: global-list interface-link only used for Springer

- toolkits/global/packages/global-lists/HISTORY.md
- toolkits/global/packages/global-lists/package.json
- toolkits/global/packages/global-lists/scss/50-components/_list-description.scss
- toolkits/global/packages/global-lists/scss/50-components/_list-group.scss
- Fix the if `is-interface` condition by adding comparison operator
- Pull `u-text-interface` out of the condition
> Hotfix global lists sass

- toolkits/global/packages/global-article/HISTORY.md
- toolkits/global/packages/global-article/package.json
- toolkits/global/packages/global-popup/HISTORY.md
- toolkits/global/packages/global-popup/package.json
- toolkits/nature/packages/nature-header/HISTORY.md
- toolkits/nature/packages/nature-header/__tests__/enhanced-header.spec.js
- toolkits/nature/packages/nature-header/js/enhanced-header.js
- toolkits/nature/packages/nature-header/package.json
Update global-expander (to get [4.0.0 changes](https://github.com/springernature/frontend-toolkits/pull/440)) in nature-header, global-popup and global-article.
Removed aria-pressed from nature-header.
Removed aria-hidden and u-js-hide from nature-header. This is handled in global-expander.
> Update global-expander in components

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/abstracts.scss
- context/brand-context/nature/scss/abstracts.scss
- context/brand-context/package.json
- context/brand-context/springer/scss/abstracts.scss
- context/brand-context/springernature/scss/abstracts.scss
This ensures that the dependency settings always come first.
> brand-context: reorder abstract imports

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/30-mixins/typography.scss
- context/brand-context/default/scss/60-utilities/typography.scss
- context/brand-context/package.json
All brands except the `default` brand were using a mixin for the heading utility classes e.g `u-h1`. This causes an issue for components that want to reference that mixin.
FIX: all the mixin to the `default` brand level, to be overridden by each imprint brand
> Update default headings to use mixins

- toolkits/global/packages/global-status-message/HISTORY.md
- toolkits/global/packages/global-status-message/package.json
- toolkits/global/packages/global-status-message/scss/10-settings/default.scss
Bugbash: https://trello.com/c/rfgoQbIM/37-is-the-line-space-ok-in-this-message-seems-a-bit-tight-compare-to-the-rest-of-the-page-rv
Increase line-height from 1.3 to 1.4 using $context--line-height-tight
> Increase line-height in global-status-message

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/30-mixins/buttons.scss
- context/brand-context/package.json
This change will make sure that any svg icon included on a button gets the currentColor used by the font.
> Button mixin svg fill

- toolkits/global/packages/global-popup/HISTORY.md
- toolkits/global/packages/global-popup/js/popup.js
- toolkits/global/packages/global-popup/package.json
- Positions the popup and arrow to be over the trigger when the trigger is positioned at the "end of line" and wraps.
- Ensures that the popup doesn't go off the screen.
- Ensures the popup appears at the correct size and isn't shrunk or stretched.
- New version number added
> Update global popup to allow for wrapped text

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/10-settings/typography.scss
- context/brand-context/package.json
Adds:
- `$context--font-size-sm`
- `$context--font-size-md`
- `$context--font-size-lg`
These variables exist in all context packages except `default` and are referenced by some global components. This meant that we get SASS compilation errors when trying to use the default brand.
> Default font-sizing bug

- toolkits/global/packages/global-status-message/HISTORY.md
- toolkits/global/packages/global-status-message/README.md
- toolkits/global/packages/global-status-message/package.json
- toolkits/global/packages/global-status-message/scss/10-settings/default.scss
- toolkits/global/packages/global-status-message/scss/50-components/status-message.scss
This PR does the following:
- Update to the latest version of the `brand-context` which fixes a bug where `$context--font-size-sm` was not available for the `default` brand
- Tidy up the README, fixing some text errors
- Add color `fill` inheritance for icons by using the `u-icon` mixin, the readme previously referenced the non-existent `c-icon` component, whilst Oscar was using the `u-icon` class. This decouples the component from any other dependencies (either another component or having to include the utility class)
> global-status-message: Add icon inheritance 

- toolkits/global/packages/global-autocomplete/HISTORY.md
- toolkits/global/packages/global-autocomplete/js/index.js
- toolkits/global/packages/global-autocomplete/package.json
This PR removes a line which focuses the autocomplete input when you click outside of it. 
This bit of code is called when you click a suggestion (updates input value and removes suggestions), or when you click outside of the component (removes suggestions) - it probably doesn't need to focus on the input.
> Dont focus input

- context/brand-context/HISTORY.md
- context/brand-context/package.json
- context/brand-context/springer/scss/30-mixins/typography.scss
Request from James to make h4 serif and consistent with the other headings
> Change h4 to serif in springer context

- toolkits/global/packages/global-card/HISTORY.md
- toolkits/global/packages/global-card/package.json
- toolkits/global/packages/global-card/scss/10-settings/nature.scss
This setting was previously in default but got changed in 3.1.0. Adding it back for nature to retain title style.
> Add global-card title overrides in nature settings

- toolkits/nature/packages/nature-header/HISTORY.md
- toolkits/nature/packages/nature-header/js/enhanced-header.js
- toolkits/nature/packages/nature-header/package.json
This change seems to allow us to remove:
```
import 'core-js/features/dom-collections';
import 'core-js/features/symbol';
import 'regenerator-runtime/runtime';
import 'core-js/stable/object/assign';
```
from header-150.js and would take the resulting bundle size from around 32kb to 7kb.
> Small refactor to generate a smaller compiled bundle size

- toolkits/global/packages/global-card/HISTORY.md
- toolkits/global/packages/global-card/package.json
- toolkits/global/packages/global-card/scss/10-settings/default.scss
- toolkits/global/packages/global-card/scss/10-settings/nature.scss
- toolkits/global/packages/global-card/scss/50-components/card.scss
- toolkits/nature/packages/nature-hero/HISTORY.md
- toolkits/nature/packages/nature-hero/package.json
- toolkits/nature/packages/nature-hero/scss/10-settings/hero.scss
- toolkits/nature/packages/nature-hero/scss/50-components/hero.scss
updates titles on nature-hero and global-card components to use fluid typography set from https://github.com/springernature/frontend-toolkits/pull/497
> Fluid typography on titles of nature-hero and global-card

- toolkits/global/packages/global-lists/HISTORY.md
- toolkits/global/packages/global-lists/README.md
- toolkits/global/packages/global-lists/package.json
- toolkits/global/packages/global-lists/scss/10-settings/_default.scss
- toolkits/global/packages/global-lists/scss/50-components/_list-header.scss
See https://github.com/springernature/frontend-toolkits/blob/6c525b43549d2be1e48f8bbb120af8e378d11f94/toolkits/global/packages/global-lists/README.md#list-header
Allows lists such as search results to have a header that includes a keyline divide, and a layout that distributes the list header's content along the horizontal axis evenly
> Adds List Header component to Global Lists

- package-lock.json
- toolkits/nature/packages/nature-sort-by/HISTORY.md
- toolkits/nature/packages/nature-sort-by/README.md
- toolkits/nature/packages/nature-sort-by/__tests__/sort-by.spec.js
- toolkits/nature/packages/nature-sort-by/js/sort-by.js
- toolkits/nature/packages/nature-sort-by/package.json
- toolkits/nature/packages/nature-sort-by/scss/10-settings/sort-by.scss
- toolkits/nature/packages/nature-sort-by/scss/50-components/sort-by.scss
- Adds a component for use on Nature product pages that displays a sort by ui menu that uses js to reload the page by modifying the url parameter for content order and reloading the page. This was preferred to making a fetch request and dynamically loading content in to the page for performance reasons (less complicated client side js). 
- Progressively enhanced, without javascript a user is able to submit the form and it will recognise the sort by option chosen.
- Uses Global Expander to open and close the menu
> Adds Nature toolkit Sort By component

- context/package-manager.json
- package-lock.json
- package.json
- toolkits/package-manager.json
- Update to the latest version of the `package-manager` which allows for tighter validation on CSS folder structure
- Update context config to fail validation if component level code included in context
- Update toolkit config to fail validation if base or utility level code included in any toolkit package
> Update package manager and create tighter css restrictions

- toolkits/springernature/packages/springernature-forms/HISTORY.md
- toolkits/springernature/packages/springernature-forms/README.md
- toolkits/springernature/packages/springernature-forms/demo/dist/index.html
- toolkits/springernature/packages/springernature-forms/demo/index.hbs
- toolkits/springernature/packages/springernature-forms/package.json
- Add some default inline `body` tag style to uniformize demo rendering in
Elements. Needed to override the Springer Nature brand default.
- Remove non necessary `.c-forms__buttons`.
- Add a note about form buttons
> Add demo body style + Remove obsolete .c-forms__buttons

- toolkits/global/packages/global-javascript/HISTORY.md
- toolkits/global/packages/global-javascript/package.json
- toolkits/global/packages/global-javascript/src/helpers/util/make-array.js
The `for in` loop was generating a non-sense array of elements in old browsers and was causing errors in the page when trying iterating over a list of DOM elements.
I changed it to a simpler way to ensure it works for all kind of lists.
> Replace for in loop in `makeArray` to iterate safely over a `NodeList`

- toolkits/global/packages/global-autocomplete/HISTORY.md
- toolkits/global/packages/global-autocomplete/js/index.js
- toolkits/global/packages/global-autocomplete/package.json
Explorer fixes:
Use 'Esc' as well as 'Escape' keycode.
Use .removeChild() rather than .remove().
> Fixes for explorer!

- toolkits/springernature/packages/springernature-header/HISTORY.md
- toolkits/springernature/packages/springernature-header/package.json
- toolkits/springernature/packages/springernature-header/scss/10-settings/layout.scss
Reduce max-width of header so that it lines up all nicely with main content.
> reduce max-width

- toolkits/springernature/packages/springernature-header/HISTORY.md
- toolkits/springernature/packages/springernature-header/package.json
- toolkits/springernature/packages/springernature-header/scss/50-components/core.scss
- toolkits/springernature/packages/springernature-header/scss/50-components/enhanced.scss
Fix errors to do with media queries
```Warning: `tablet-wide-width` is not a valid breakpoint name.
node_modules/@springernature/brand-context/default/scss/30-mixins/media-query.scss 17:3        -get-breakpoint()
node_modules/@springernature/brand-context/default/scss/30-mixins/media-query.scss 76:22       media-query()
node_modules/@springernature/brand-context/springernature/scss/30-mixins/media-query.scss 8:2  from-wide-tablet()
node_modules/@springernature/springernature-header/scss/50-components/enhanced.scss 37:3       @import
src/main/sass/main.scss 31:9                                                                   root stylesheet```
> Correct error - `tablet-wide-width` is not a valid breakpoint name.

- toolkits/global/packages/global-lists/HISTORY.md
- toolkits/global/packages/global-lists/package.json
- toolkits/global/packages/global-lists/scss/10-settings/_springer.scss
We use margin-bottom on the default brand of this component. However when used on Springer branded sites it is not needed. I'm not sure who is consuming this global component so I'm cautiously only removing the bottom margin on the Springer brand instead of default.
> Removes bottom margin from list description terms on springer brand

- toolkits/springernature/packages/springernature-header/HISTORY.md
- toolkits/springernature/packages/springernature-header/package.json
- toolkits/springernature/packages/springernature-header/scss/10-settings/layout.scss
This commit reverts a change to the header width. A subsequent fix I made to the media queries means that this change is not needed anymore.
> reverts width change

- context/brand-context/HISTORY.md
- context/brand-context/package.json
- context/brand-context/springer/scss/abstracts.scss
Forgot to do this on previous PR (yesterday re keyline changes). Needed to ensure Springer brand uses correct greyscale values.
> Imports style 10-settings in to Springer abstracts partial

- toolkits/springernature/packages/springernature-submission-header/HISTORY.md
- toolkits/springernature/packages/springernature-submission-header/package.json
- toolkits/springernature/packages/springernature-submission-header/scss/50-components/enhanced.scss
Remove flex from authors list at small breakpoint.
Remove it entirely from metadata row at top as they're all inline anyway.
> Remove flex from sm breakpoint

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/30-mixins/focus.scss
- context/brand-context/nature/scss/40-base/links.scss
- context/brand-context/package.json
* Add parameter for reflow on focus mixin
- applied on links as this seems to be where outline appears incorrectly
- related to 13.1.2
* Fix `:focus` being applied twice on `a`
> Add parameter for reflow on focus mixin 

- toolkits/global/packages/global-skip-link/HISTORY.md
- toolkits/global/packages/global-skip-link/README.md
- toolkits/global/packages/global-skip-link/package.json
- toolkits/global/packages/global-skip-link/scss/10-settings/_springer.scss
- add springer brand in settings to use for springer and bmc/so
- bump brand-context to the latest
> add springer brand to global-skip-link

- toolkits/springernature/packages/springernature-submission-header/HISTORY.md
- toolkits/springernature/packages/springernature-submission-header/package.json
- toolkits/springernature/packages/springernature-submission-header/scss/50-components/enhanced.scss
- toolkits/springernature/packages/springernature-submission-header/view/header.hbs
Remove the slightly complicated addition of comma separators in the SCSS. Add them in the template instead.
And move the author background to a variable.
> Use commas in template rather than scss

- toolkits/springernature/packages/springernature-header/HISTORY.md
- toolkits/springernature/packages/springernature-header/package.json
- toolkits/springernature/packages/springernature-header/scss/50-components/enhanced.scss
Some new journals with larger logo images were getting squished.
> Increase max width of journal logo

- toolkits/springernature/packages/springernature-submission-header/HISTORY.md
- toolkits/springernature/packages/springernature-submission-header/package.json
- toolkits/springernature/packages/springernature-submission-header/scss/50-components/enhanced.scss
Smol smol vertical position tweak
Move it down  pixel to line up nicely. Make it absolute so it doesn't push down the text (which it is only doing when it is the last item??)
-->
> Positioning of author icon

- toolkits/springernature/packages/springernature-header/HISTORY.md
- toolkits/springernature/packages/springernature-header/package.json
- toolkits/springernature/packages/springernature-header/scss/50-components/enhanced.scss
We try to accommodate different sized logos at different breakpoints. One logo in particular with a lot of whitespace at the end has illustrated a bit of a problem whereby it gets shrunk quite small at smaller breakpoints. 
Below you can see the green-bordered SVG which seems to have been set to have ~40% whitespace?
--->
> Accommodate diff sized logos at breakpoints

- toolkits/springernature/packages/springernature-header/HISTORY.md
- toolkits/springernature/packages/springernature-header/package.json
- toolkits/springernature/packages/springernature-header/scss/50-components/enhanced.scss
After fixing the logo sizing in a previous commit, I noticed it was still a bit squiffy when js disabled.
This fix basically adjust the widths/floating for non-js.
> Improve logo sizing for non-js view

- toolkits/global/packages/global-corporate-footer/README.md
- toolkits/springer/packages/springer-publisher-footer/HISTORY.md
- toolkits/springer/packages/springer-publisher-footer/README.md
- toolkits/springer/packages/springer-publisher-footer/demo/index.hbs
- toolkits/springer/packages/springer-publisher-footer/package.json
Removes `<footer>` from the `springer-publisher-footer` template to avoid nested footers when combined with `global-corporate-footer`.
> Footer landmark

- toolkits/global/packages/global-layout-with-sidebar/HISTORY.md
- toolkits/global/packages/global-layout-with-sidebar/package.json
- toolkits/global/packages/global-layout-with-sidebar/scss/10-settings/nature.scss
- toolkits/global/packages/global-layout-with-sidebar/scss/10-settings/springer.scss
We're going to start using this toolkit for the layout in the articles, chapter and book pages in Springerlink and nature. So I added the settings for them.
> Added settings for nature and springer

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/30-mixins/icons.scss
- context/brand-context/package.json
Adding the option to change size as the default `1em` made some existing icons smaller than before.
> Add optional width and height to set for u-icon mixin

- toolkits/global/packages/global-status-message/HISTORY.md
- toolkits/global/packages/global-status-message/demo/dist/index.html
- toolkits/global/packages/global-status-message/package.json
- toolkits/global/packages/global-status-message/scss/10-settings/default.scss
- toolkits/global/packages/global-status-message/scss/50-components/status-message.scss
override sizes from `u-icon` which made the status icon a bit smaller than the original design
> add icon size settings for global-status-message 

- toolkits/global/packages/global-autocomplete/HISTORY.md
- toolkits/global/packages/global-autocomplete/__tests__/index.js
- toolkits/global/packages/global-autocomplete/js/index.js
- toolkits/global/packages/global-autocomplete/package.json
This fix allows the default expected behaviour from the Tab keypress, i.e move focus to next focussable element, rather than scroll through the results list.
> Allow default tab behaviour

- context/brand-context/HISTORY.md
- context/brand-context/package.json
- context/brand-context/springer/scss/10-settings/keyframes.scss
- context/brand-context/springer/scss/abstracts.scss
Adding keyframes to the springer brand it can then be removed from multiple scss files it sits within across oscar article stylesheets
> Add keyframes to springer brand context

- toolkits/springernature/packages/springernature-modal/HISTORY.md
- toolkits/springernature/packages/springernature-modal/package.json
- toolkits/springernature/packages/springernature-modal/scss/50-components/enhanced.scss
I came across an issue where I had some elements on the page that had
an z-index and these were bleeding through the modal. To overcome this,
I added a z-index to the modal when its in open state and increased the
index to a stupidly high number so its less likely other elements on
the page may ever bleed through again.
> Fix page elements bleeding through springernature-modal

- toolkits/global/packages/global-meta/HISTORY.md
- toolkits/global/packages/global-meta/package.json
We move the version of the `global-meta` component to use an older version of the `brandContext` so that it we could get Travis to pass the tests.
Now we've done that, this PR just updates the version of the Brand Context that should be used to the latest - `18.1.1`
> the one that updates version of global-meta brand context version required

- context/brand-context/HISTORY.md
- context/brand-context/package.json
- context/brand-context/springer/scss/40-base/layout.scss
Fixes an `em` value that still thinks the root font-size is `62.5%` to a `rem` unit knowing the root font-size is `100%`.
I was so preoccupied with wether or not I had changed all the `rem` values, I didn't stop to think about `em`s.
> the final? fix for font-sizing

- toolkits/springernature/packages/springernature-user-details/HISTORY.md
- toolkits/springernature/packages/springernature-user-details/package.json
- toolkits/springernature/packages/springernature-user-details/scss/50-components/core.scss
- toolkits/springernature/packages/springernature-user-details/scss/50-components/enhanced.scss
For non-js environment, the logout link was the same colour as the background on hover. This style should be in the .js version, as one or two others.
no JS
JS
> Fix styling for non-js

- toolkits/springernature/packages/springernature-user-details/HISTORY.md
- toolkits/springernature/packages/springernature-user-details/README.md
- toolkits/springernature/packages/springernature-user-details/package.json
- toolkits/springernature/packages/springernature-user-details/scss/50-components/core.scss
- toolkits/springernature/packages/springernature-user-details/scss/50-components/enhanced.scss
While implementing this component to a few services in OASiS, I came across these two issues with this component.
Firstly there was no focus state on the "button" that the user users to trigger the dropdown. The default focus state being used looks jagged and doesn't match other elements on the page that might be using yellow focus state. 
Another issue related to relying on outside influences to control font family being used for this component. A component should have complete control over how it looks and behaves.
- Fixes issue with focus state for SpringerNature-User-Details component
- Sets the font family needed for SpringerNature-User-Details component
> Font and focus state improvements for SpringerNature-User-Details

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/abstracts.scss
- context/brand-context/package.json
While implementing SpringerNature brand-context to OASiS I discovered
that some functions and mixins where not being included in the abstract
mean that a developer would have to manually import these functions.
> Add missing functions and mixins to default brand abstracts

- toolkits/springernature/packages/springernature-forms/HISTORY.md
- toolkits/springernature/packages/springernature-forms/package.json
- toolkits/springernature/packages/springernature-header/HISTORY.md
- toolkits/springernature/packages/springernature-header/package.json
- toolkits/springernature/packages/springernature-modal/HISTORY.md
- toolkits/springernature/packages/springernature-modal/package.json
- toolkits/springernature/packages/springernature-submission-header/HISTORY.md
- toolkits/springernature/packages/springernature-submission-header/package.json
- toolkits/springernature/packages/springernature-user-details/HISTORY.md
- toolkits/springernature/packages/springernature-user-details/package.json
During the publication of packages, we previously added a `post-install` step to provide messaging around the use of the `brand-context` package. This functionality has [now been removed](https://github.com/springernature/frontend-package-manager/pull/81) due to causing issues in our CI environments.
In order to remove this from published packages, we need to publish new versions of each package - no code changes are needed as the `post-install` was added via the `frontend-package-manager`, and a new version will now just miss out that step.
This PR bumps the version for each package in the Springer Nature toolkit.
> Springernature: remove `post-install` step from `package.json`

- toolkits/global/packages/global-grid/HISTORY.md
- toolkits/global/packages/global-grid/README.md
- toolkits/global/packages/global-grid/package.json
v2 causes an issue when used with dart-sass as there is a [syntax error with one of the @warns](https://github.com/thoughtbot/neat/blob/2bde983e693a05edce1acc128ebb278e9058c7dc/core/neat/mixins/_grid-container.scss#L22-L23)
This issue was fixed in [v3](https://github.com/thoughtbot/neat/blob/2bde983e693a05edce1acc128ebb278e9058c7dc/core/neat/mixins/_grid-container.scss#L22-L23).
Seeing as bourbon-neat hasn't been updated for years it seems practical to use the last latest release
> global-grid: update bourbon-neat v2 to v4

- toolkits/springer/packages/springer-dropdown/HISTORY.md
- toolkits/springer/packages/springer-dropdown/package.json
- toolkits/springer/packages/springer-header/HISTORY.md
- toolkits/springer/packages/springer-header/package.json
- toolkits/springer/packages/springer-hero/HISTORY.md
- toolkits/springer/packages/springer-hero/package.json
- toolkits/springer/packages/springer-listing/HISTORY.md
- toolkits/springer/packages/springer-listing/package.json
- toolkits/springer/packages/springer-media/HISTORY.md
- toolkits/springer/packages/springer-media/package.json
- toolkits/springer/packages/springer-product-header/HISTORY.md
- toolkits/springer/packages/springer-product-header/package.json
- toolkits/springer/packages/springer-publisher-footer/HISTORY.md
- toolkits/springer/packages/springer-publisher-footer/package.json
- toolkits/springer/packages/springer-user-metadata/HISTORY.md
- toolkits/springer/packages/springer-user-metadata/package.json
- toolkits/springer/packages/springer-webfonts/HISTORY.md
- toolkits/springer/packages/springer-webfonts/package.json
During the publication of packages, we previously added a `post-install` step to provide messaging around the use of the `brand-context` package. This functionality has [now been removed](https://github.com/springernature/frontend-package-manager/pull/81) due to causing issues in our CI environments.
In order to remove this from published packages, we need to publish new versions of each package - no code changes are needed as the `post-install` was added via the `frontend-package-manager`, and a new version will now just miss out that step.
This PR bumps the version for each package in the **Springer** toolkit.
> Springer: remove `post-install` step from `package.json`

- toolkits/global/packages/global-card/HISTORY.md
- toolkits/global/packages/global-card/package.json
- toolkits/global/packages/global-card/scss/50-components/card.scss
I found out this class is hugely used across different nature pages so we need it to put it back.
> Put back --flush modifier to reset padding in the card__body

- toolkits/global/packages/global-autocomplete/HISTORY.md
- toolkits/global/packages/global-autocomplete/demo/dist/index.html
- toolkits/global/packages/global-autocomplete/demo/main.js
- toolkits/global/packages/global-autocomplete/package.json
* BUG: unable to move focus to select autocomplete items when using NVDA with Firefox (Windows) 
* add role="listbox" to parent container of autocomplete items
* add role="option" to each autocomplete item  
* Change tabIndex value from string to integer
> Fix focus of autocomplete items for NVDA with Firefox (Windows)

- toolkits/nature/packages/nature-footer/HISTORY.md
- toolkits/nature/packages/nature-footer/package.json
- toolkits/nature/packages/nature-header/HISTORY.md
- toolkits/nature/packages/nature-header/package.json
- toolkits/nature/packages/nature-hero/HISTORY.md
- toolkits/nature/packages/nature-hero/package.json
- toolkits/nature/packages/nature-section-heading/HISTORY.md
- toolkits/nature/packages/nature-section-heading/package.json
- toolkits/nature/packages/nature-sort-by/HISTORY.md
- toolkits/nature/packages/nature-sort-by/package.json
This is needed to remove the post-install step during package publication, as npx commands for `@springernature/util-context-warning` cause issues in CI
> Updates nature components to ensure no post-install step

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/10-settings/colors/shared.scss
- context/brand-context/package.json
- context/brand-context/springernature/scss/10-settings/colors/default.scss
The Springer Nature Corporate colours used to live in the `springernature` brand context. For the new `global-corporate-footer` they need to be available to all brands.
This PR moves the colours to `colors/shared.scss` in the default brand context, then references them directly in the `springernature` brand context so as to make this a non-destructive change.
> Share Springer Nature Corporate colours globally

- context/brand-context/HISTORY.md
- context/brand-context/default/README.md
- context/brand-context/default/__tests__/unit/dom/expander/expander.spec.js
- context/brand-context/default/__tests__/unit/dom/expander/index.spec.js
- context/brand-context/default/__tests__/unit/dom/get-data-options.spec.js
- context/brand-context/default/__tests__/unit/util/create-event.spec.js
- context/brand-context/default/__tests__/unit/util/debounce.spec.js
- context/brand-context/default/__tests__/unit/util/delete-cookie.spec.js
- context/brand-context/default/__tests__/unit/util/get-cookie.spec.js
- context/brand-context/default/__tests__/unit/util/make-array.spec.js
- context/brand-context/default/__tests__/unit/util/onetrust.spec.js
- context/brand-context/default/__tests__/unit/util/set-cookie.spec.js
- context/brand-context/default/__tests__/unit/util/throttle.spec.js
- context/brand-context/default/js/README.md
- context/brand-context/default/js/helpers/dom/expander/_expander.js
- context/brand-context/default/js/helpers/dom/expander/index.js
- context/brand-context/default/js/helpers/dom/get-data-options.js
- context/brand-context/default/js/helpers/index.js
- context/brand-context/default/js/helpers/util/create-event.js
- context/brand-context/default/js/helpers/util/debounce.js
- context/brand-context/default/js/helpers/util/delete-cookie.js
- context/brand-context/default/js/helpers/util/get-cookie.js
- context/brand-context/default/js/helpers/util/make-array.js
- context/brand-context/default/js/helpers/util/onetrust.js
- context/brand-context/default/js/helpers/util/set-cookie.js
- context/brand-context/default/js/helpers/util/throttle.js
- context/brand-context/package.json
- context/package-manager.json
This PR adds the following to the `brand-context`:
- The contents of the `global-javascript` component
- The contents of the `global-expander` component
Work to do after this PR:
- Deprecate `global-javascript`
- Deprecate `global-expander`
> Move shared javascript into the brand-context

- toolkits/global/packages/global-corporate-footer/HISTORY.md
- toolkits/global/packages/global-corporate-footer/package.json
- toolkits/global/packages/global-corporate-footer/scss/10-settings/default.scss
- Update to latest version of the `brand-context`
- This version includes the corporate brand colours shared within the default level, so we can now use that here
> global-corporate-footer: update brand-context

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/00-tokens/_background.variables.scss
- context/brand-context/default/scss/00-tokens/_border.variables.scss
- context/brand-context/default/scss/00-tokens/_breakpoints.variables.scss
- context/brand-context/default/scss/00-tokens/_button.variables.scss
- context/brand-context/default/scss/00-tokens/_link.variables.scss
- context/brand-context/default/scss/00-tokens/_sizing.variables.scss
- context/brand-context/default/scss/00-tokens/_spacing.variables.scss
- context/brand-context/default/scss/00-tokens/_state.variables.scss
- context/brand-context/default/scss/00-tokens/_text.variables.scss
- context/brand-context/nature/scss/00-tokens/_illustration.variables.scss
- context/brand-context/nature/scss/00-tokens/_typography.variables.scss
- context/brand-context/package.json
- context/brand-context/springer/scss/00-tokens/_typography.variables.scss
- context/brand-context/springernature/scss/00-tokens/_breakpoints.variables.scss
- context/brand-context/springernature/scss/00-tokens/_typography.variables.scss
- context/design-tokens/alias/default/background/background.json
@morgaan reached out with a but that was producing 
`$tokens--background-container: color.white};`
looks like we missed a curly bracket in a `.json` file. 
This PR fixes that.
To make sure this doesn't happen in future - I'm investigating ways to 'test' the `.json` so it adheres to some sort of spec. 
🙏🖤
> adds curly brace to missing design tokens value

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/00-tokens/_background.variables.scss
- context/brand-context/default/scss/00-tokens/_border.variables.scss
- context/brand-context/default/scss/00-tokens/_breakpoints.variables.scss
- context/brand-context/default/scss/00-tokens/_button.variables.scss
- context/brand-context/default/scss/00-tokens/_index.scss
- context/brand-context/default/scss/00-tokens/_link.variables.scss
- context/brand-context/default/scss/00-tokens/_sizing.variables.scss
- context/brand-context/default/scss/00-tokens/_spacing.variables.scss
- context/brand-context/default/scss/00-tokens/_state.variables.scss
- context/brand-context/default/scss/00-tokens/_text.variables.scss
- context/brand-context/nature/scss/00-tokens/_illustration.variables.scss
- context/brand-context/nature/scss/00-tokens/_index.scss
- context/brand-context/nature/scss/00-tokens/_typography.variables.scss
- context/brand-context/package.json
- context/brand-context/springer/scss/00-tokens/_index.scss
- context/brand-context/springer/scss/00-tokens/_typography.variables.scss
- context/brand-context/springernature/scss/00-tokens/_breakpoints.variables.scss
- context/brand-context/springernature/scss/00-tokens/_index.scss
- context/brand-context/springernature/scss/00-tokens/_typography.variables.scss
It appears my little bit of JS to generate a manifest file for each brands set of tokens has regressed and is now including itself in the list of `@imports` 
This PR is a 'hotfix' (I guess) as I've manually removed the `@import "_index.scss" for each brands `00-tokens`. 
I've run a local Sass compile and it's not erroring now. 
🙏🖤
> manually removes `_index.scss` file from the `_index.scss` file

- context/brand-context/HISTORY.md
- context/brand-context/package.json
- context/brand-context/springer/scss/10-settings/typography.scss
The furniture font size was incorrectly `1rem`. Since we hack the `body` size for an old Chrome bug it should be `1.125rem`, hence this PR!
> using default base size of 1.125rem

- toolkits/springer/packages/springer-hero/HISTORY.md
- toolkits/springer/packages/springer-hero/README.md
- toolkits/springer/packages/springer-hero/demo/context.json
- toolkits/springer/packages/springer-hero/demo/dist/index.html
- toolkits/springer/packages/springer-hero/demo/index.hbs
- toolkits/springer/packages/springer-hero/package.json
- toolkits/springer/packages/springer-hero/view/springer-hero.hbs
```
* Image and content now optional
```
Changed the template logic to reflect how people use the CMS.
> Springer Hero image and content now optional

- context/brand-context/HISTORY.md
- context/brand-context/package.json
- context/brand-context/springer/scss/40-base/typography.scss
```
* Left aligns basic lists in the springer context
```
`0.9em` feels magic numbery 😬 but I tested across multiple fonts and font-sizes and it is the most reliable value.
```
/* Basic lists should be aligned to the left */
ul:not([class]),
ol:not([class]) {
/* Allow for bullet itself */
padding-left: 0.9em;
}
```
> uses negation to left align lists without classes

- context/brand-context/HISTORY.md
- context/brand-context/package.json
- context/brand-context/springernature/scss/10-settings/breakpoints.scss
Related to https://github.com/springernature/frontend-open-space/issues/307
This open space issue was discussed 17/03/2022. 
Any thoughts about this change? Is it something we could merge?
> Fix SpringerNature breakpoints so theres no conflict between Default and SpringerNature components

- toolkits/global/packages/global-card/HISTORY.md
- toolkits/global/packages/global-card/demo/context.json
- toolkits/global/packages/global-card/demo/dist/index.html
- toolkits/global/packages/global-card/demo/main.scss
- toolkits/global/packages/global-card/package.json
- toolkits/global/packages/global-card/scss/50-components/card.scss
* The fallback for IE did not work quite as expected in real IE11
* This has been addressed by removing a `transform` and setting an explicit `left: 0` for the positioning
> IE image fix

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/00-tokens/_background.variables.scss
- context/brand-context/default/scss/00-tokens/_border.variables.scss
- context/brand-context/default/scss/00-tokens/_breakpoints.variables.scss
- context/brand-context/default/scss/00-tokens/_button.variables.scss
- context/brand-context/default/scss/00-tokens/_link.variables.scss
- context/brand-context/default/scss/00-tokens/_sizing.variables.scss
- context/brand-context/default/scss/00-tokens/_spacing.variables.scss
- context/brand-context/default/scss/00-tokens/_state.variables.scss
- context/brand-context/default/scss/00-tokens/_text.variables.scss
- context/brand-context/nature/scss/00-tokens/_illustration.variables.scss
- context/brand-context/nature/scss/00-tokens/_typography.variables.scss
- context/brand-context/package.json
- context/brand-context/springer/scss/00-tokens/_index.scss
- context/brand-context/springer/scss/00-tokens/_typography.variables.scss
- context/brand-context/springernature/scss/00-tokens/_breakpoints.variables.scss
- context/brand-context/springernature/scss/00-tokens/_typography.variables.scss
- context/design-tokens/alias/default/background/background.json
- context/design-tokens/alias/default/border/border.json
- context/design-tokens/alias/default/button/button.json
- context/design-tokens/alias/default/link/link.json
- context/design-tokens/alias/nature/illustration/illustration.json
- context/design-tokens/alias/nature/typography/typography.json
- context/design-tokens/literal/default/color/color.json
@foxintherain has recently made some updates to the Sketch files to make sure they're consistent with the Design Tokens naming convention. They noticed some errors that have been rectified. This PR updates to match the [updated styleguide in Sketch](https://www.sketch.com/s/fa9c2fc9-a179-43f0-b21e-9562c9c17c0c/p/F36D7BB7-BA2F-4E89-BB54-80C7DB72A707).
- `colors.primary.bright-blue` token (#0088CC).
- default focus style to use new `colors.primary.bright-blue`.
---
- `border.color.indent` token for use with indent global form elements.
- adds H4 and H5 typographic styles for Nature.
- `border.color.primary` token to reference `color.grayscale.800`.
- primary and secondary button colours.
- text link `visited` and `focus` styles.
- `004` and `005` variants of illustration colours for Nature. …
> small updates to literal and alias design tokens

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/00-tokens/_background.variables.scss
- context/brand-context/default/scss/00-tokens/_border.variables.scss
- context/brand-context/default/scss/00-tokens/_breakpoints.variables.scss
- context/brand-context/default/scss/00-tokens/_button.variables.scss
- context/brand-context/default/scss/00-tokens/_link.variables.scss
- context/brand-context/default/scss/00-tokens/_sizing.variables.scss
- context/brand-context/default/scss/00-tokens/_spacing.variables.scss
- context/brand-context/default/scss/00-tokens/_state.variables.scss
- context/brand-context/default/scss/00-tokens/_text.variables.scss
- context/brand-context/nature/scss/00-tokens/_illustration.variables.scss
- context/brand-context/nature/scss/00-tokens/_typography.variables.scss
- context/brand-context/package.json
- context/brand-context/springer/scss/00-tokens/_index.scss
- context/brand-context/springer/scss/00-tokens/_typography.variables.scss
- context/brand-context/springernature/scss/00-tokens/_breakpoints.variables.scss
- context/brand-context/springernature/scss/00-tokens/_typography.variables.scss
- context/design-tokens/alias/default/background/background.json
- context/design-tokens/alias/default/border/border.json
- context/design-tokens/literal/default/sizing/sizing.json
- context/design-tokens/literal/default/spacing/spacing.json
Whilst creating #758 so that the Design Tokens and the compiled Sass match what is in [the current Sketch file](https://www.sketch.com/s/fa9c2fc9-a179-43f0-b21e-9562c9c17c0c) I had forgotten changes that were being made that would have been in place (had I not created and merged #758). 
These token changes were made to accommodate the new `global-forms` component and allow @Heydon to work swiftly without waiting for updates. 
However, as mentioned #758 kinda screwed that up. This PR should fix it.
We have introduced both `relative` and `absolute` spacing and sizing tokens for times you need exact pixel values rather than using the `rem` unit. 
Before you would use `{spacing.400}` (and eventually `$spacing-400`) you would now using `{spacing.absolute.400}` for `16px` and …
> more token updates needed.

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/40-base/normalize.scss
- context/brand-context/package.json
Reduces file size (uncompressed) from 8KB to 6KB.
The main difference really is dropping all the lte IE 9 support hacks.
(https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md)
v5 was released way back in 2016 and v8 was released way back in 2018.
The repo doesn't seem be maintained and questions asked by the community
seem to support that assumption (https://github.com/necolas/normalize.css/issues/880)
Theres a bigger question of whether this is the approach we still want to
use or perhaps investigate whether there is a modern normalizer out there some
where. In the issue I linked to there are a couple of suggestions at alternative
ones that we could look at.
> Bump normalize version from v5 to v8

- toolkits/nature/packages/nature-section-heading/HISTORY.md
- toolkits/nature/packages/nature-section-heading/README.md
- toolkits/nature/packages/nature-section-heading/demo/dist/index.html
- toolkits/nature/packages/nature-section-heading/demo/index.hbs
- toolkits/nature/packages/nature-section-heading/package.json
- toolkits/nature/packages/nature-section-heading/view/section-heading.hbs
This PR:
* assigns sensible default heading levels to Section heading variants with option to override
* adds guidance on when to use variants with and without top border
* adds guidance on overriding default heading levels
* updates guidance on adding chevron icon to section headings as link
> Section heading docs

- toolkits/global/packages/global-forms/HISTORY.md
- toolkits/global/packages/global-forms/demo/context.json
- toolkits/global/packages/global-forms/demo/dist/index.html
- toolkits/global/packages/global-forms/package.json
- toolkits/global/packages/global-forms/scss/50-components/_forms.scss
- toolkits/global/packages/global-forms/view/fields/globalFormHidden.hbs
- toolkits/springer/packages/springer-hero/package.json
```
* `hidden` input type
* `pointer-events: none` to make select clickable through chevron
```
> Global forms hidden input

- toolkits/global/packages/global-details/HISTORY.md
- toolkits/global/packages/global-details/demo/dist/index.html
- toolkits/global/packages/global-details/demo/main.scss
- toolkits/global/packages/global-details/package.json
- toolkits/global/packages/global-details/scss/10-settings/springer.scss
- toolkits/global/packages/global-details/scss/10-settings/springernature.scss
- toolkits/global/packages/global-details/scss/50-components/details.scss
```
* Alignment of chevron icon to baseline
```
Before (springer example):
After (springer example):
> Details icon alignment

- context/brand-context/HISTORY.md
- context/brand-context/package.json
- context/brand-context/springer/scss/30-mixins/typography.scss
- context/brand-context/springer/scss/40-base/basic.scss
- context/brand-context/springer/scss/40-base/typography.scss
```
* BREAKING:
* Springer: erroneous use of placeholders removed to fix cascade
* Springer: new spacing algorithm for flow elements
* Removal of `outline: none` for non-interactive elements (redundant)
```
> Springer flow spacing

- context/design-tokens/build-component.js
- package.json
Because there are currently no brand specific components that make use of design tokens I had an empty `''` in the `build-component.js` file which would create a `package/package` folder in toolkits. 
This is a hotfix becuase I'm working on a better tokens workflow with #763. 
I have removed the brand components task from being run when running `npm run tokens:component`.
I have commented out the erroneous code.
> Fixes `packages/packages` error when running full tokens build.

- toolkits/global/packages/global-card/HISTORY.md
- toolkits/global/packages/global-card/package.json
- toolkits/global/packages/global-card/scss/50-components/card.scss
So... we hyphenate long German words where `de` is correctly set as the `lang` but... there are many pages that don't currently set the `lang` correctly, so this is damage control.
> stop overflow on global-card

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/40-base/basic.scss
- context/brand-context/default/scss/core.scss
- context/brand-context/nature/scss/40-base/basic.scss
- context/brand-context/nature/scss/core.scss
- context/brand-context/package.json
- context/brand-context/springer/scss/40-base/basic.scss
- context/brand-context/springer/scss/core.scss
- context/brand-context/springernature/scss/40-base/basic.scss
- context/brand-context/springernature/scss/core.scss
Thanks to @morgaan  for raising an issue in https://github.com/springernature/frontend-toolkits/pull/792 which highlighted the need for us to be setting a sensible default width and height for all decorative inline SVGs in our core styles.
In some cases we use inline SVGs on our sites and style them in our enhanced stylesheets. Those enhanced styles often set an appropriate width and height for the inline SVG. It makes sense to have a sensible default in the core styles, this prevent the core browser user experience from looking a bit broken (because of huge SVGs that have scaled to the size of their container).
> Sensible width and height for aria-hidden SVGs in core browser styles

- toolkits/global/packages/global-forms/HISTORY.md
- toolkits/global/packages/global-forms/demo/context.json
- toolkits/global/packages/global-forms/demo/dist/index.html
- toolkits/global/packages/global-forms/package.json
- toolkits/global/packages/global-forms/scss/50-components/_forms.scss
- toolkits/global/packages/global-forms/view/fields/globalFormRadios.hbs
- toolkits/global/packages/global-forms/view/fields/globalFormSelect.hbs
```
* Removes margin-top from form labels used on pictographic radios when in horizontal layout
* Fixes layout issue with display of error information for pictographic radio groups
```
> Global forms RC10

- context/brand-context/HISTORY.md
- context/brand-context/nature/scss/abstracts.scss
- context/brand-context/nature/scss/core.scss
- context/brand-context/nature/scss/enhanced.scss
- context/brand-context/package.json
- context/brand-context/springer/scss/abstracts.scss
- context/brand-context/springer/scss/core.scss
- context/brand-context/springer/scss/enhanced.scss
- context/brand-context/springernature/scss/abstracts.scss
- context/brand-context/springernature/scss/core.scss
- context/brand-context/springernature/scss/enhanced.scss
For the `brand-context` the "abstracts" (functions, variables, mixins - anything that doesn't compile to CSS) are split into their own file. The brand (nature, springer, springernature) endpoints _extend_ the default brand so need to include the context abstracts from there first. Currently the abstracts are imported into the `core` and `enhanced` endpoints by including the default first, then the relevant brand.
There is currently some work being done to provide compiled CSS and JS within components as a different method for using them in your app. As part of that process we need to use the abstracts endpoint in order to compile the CSS from a component, and currently this means including the default AND the brand abstracts, and setting the correct loadPaths for everything to compile …
> Refactor brand context abstracts

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/40-base/basic.scss
- context/brand-context/package.json
The introduction of this style had oversights:
1. It has a higher specificity score than classnames because it is two selectors (an element selector and an attribute selector)
2. Having any default SVG styles for sizing means that html attributes cannot be used to size SVGs because the style always overrides the width and height html attributes
Therefore I think it should be removed
> Removes default SVG sizing from core styles

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/60-utilities/typography.scss
- context/brand-context/package.json
Since upgrading to a version of brand-context which includes the block spacing styles we (pandora/orion/ecommerce) have been finding a few places where `margin-block-start` is creating unwanted spaces (before page headers, inside buttons etc...).
Given the specificity of the selectors for the block spacing it can't simply be overridden from within a class. This change provides a utility to brute force it back to 0 for places where it's needed.
> Add a utility class to reset margin-block-start

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/40-base/block-spacing.scss
- context/brand-context/package.json
Ensures that the `margin-block-start` is only applied to classnames _starting with_ `c-` not _containing_ `c-`.
> Default brand context: tighten block spacing selector for c-

- .travis.yml
- CONTRIBUTING.md
The default branch name reflects an unsympathetic use of language and is not in line with our recommendations.
I'm happy to do the default branch rename just before merging this PR, but are there other systems outside the scope of this repo which might break as and when we rename? @alexkilgour
> supports default branch rename

- toolkits/global/packages/global-popup/HISTORY.md
- toolkits/global/packages/global-popup/package.json
- toolkits/global/packages/global-popup/scss/10-settings/_default.scss
After a conversation with [Carlos Mucharaz in the #accessiblity channel](https://springernature.slack.com/archives/C9MS96R7T/p1665568412838009), we noticed that the border to the popup component is not accessible, having the minimum contrast ration less than 3:1. 
This PR changes the border color from `rgba(151, 191, 216, .3)` to use the token color `$t-border-color-primary`, a [core color for border](https://elements.springernature.com/springernature/styleguide/color#borders) that is compatible with all brands.
> Fix popup border color to be accessible

- toolkits/global/packages/global-footer/HISTORY.md
- toolkits/global/packages/global-footer/package.json
- toolkits/global/packages/global-footer/scss/10-settings/default.scss
- toolkits/global/packages/global-footer/scss/50-components/footer.scss
because, currently, the elements site and the demos created for it make use of only the default context for global components it transpires that because nature.com has a line height of `1.76` on the `html` element whereas we would/could expect it to be `1.15` it looks massive.
This PR adds the line-height to the `c-footer` class which should override the html across brands so that it matches what has been the expectation (the `defautl` context)
> specifies the line height because of nature

- context/design-tokens/components/global/global-customer-satisfaction-input/default.json
- toolkits/global/packages/global-customer-satisfaction-input/HISTORY.md
- toolkits/global/packages/global-customer-satisfaction-input/README.md
- toolkits/global/packages/global-customer-satisfaction-input/__tests__/customer-satisfaction-input.spec.js
- toolkits/global/packages/global-customer-satisfaction-input/demo/context.json
- toolkits/global/packages/global-customer-satisfaction-input/demo/dist/index.html
- toolkits/global/packages/global-customer-satisfaction-input/demo/index.hbs
- toolkits/global/packages/global-customer-satisfaction-input/demo/main.js
- toolkits/global/packages/global-customer-satisfaction-input/demo/main.scss
- toolkits/global/packages/global-customer-satisfaction-input/demo/scss/_demo-page-layout.scss
- toolkits/global/packages/global-customer-satisfaction-input/js/customer-satisfaction-input.js
- toolkits/global/packages/global-customer-satisfaction-input/js/index.js
- toolkits/global/packages/global-customer-satisfaction-input/package.json
- toolkits/global/packages/global-customer-satisfaction-input/scss/00-tokens/_default.tokens.scss
- toolkits/global/packages/global-customer-satisfaction-input/scss/30-mixins/_customer-satisfaction-input-button.scss
- toolkits/global/packages/global-customer-satisfaction-input/scss/50-components/_customer-satisfaction-input.scss
- toolkits/global/packages/global-customer-satisfaction-input/view/customerSatisfactionInput.hbs
This replaces the Global Ratings Survey component which we decided to rename. Global Ratings Survey will be deprecated in a [subsequent PR](https://github.com/springernature/frontend-toolkits/pull/851).
The code committed here is the same as Global Ratings Survey albeit with different naming applied throughout. This component also remains dependent on the same version of Brand Context as Global Ratings Survey, version 29.0.3. Adopting a new version of BC is on hold pending some changes that need to happen in Elements and as such this will be done in a subsequent PR.
At this time I am the only consumer of this component. But soon other teams will start consuming it so it is good to do this rename now.
**Why are we renaming the component?**
I have worked closely with the Elements team on …
> Adds the Global Customer Satisfaction Input component

- toolkits/springernature/packages/springernature-header/HISTORY.md
- toolkits/springernature/packages/springernature-header/README.md
- toolkits/springernature/packages/springernature-header/package.json
- toolkits/springernature/packages/springernature-header/scss/10-settings/layout.scss
- toolkits/springernature/packages/springernature-header/scss/50-components/core.scss
- toolkits/springernature/packages/springernature-header/scss/50-components/enhanced.scss
- toolkits/springernature/packages/springernature-header/view/header.hbs
I have removed references to the user-details component, as this has been replaced with the Identity component.
I moved some styles from core.scss to enhanced.scss.
I moved top padding from .c-header to .c-header__inner.
I tidied some of the rules around sizing for the logos.
> Remove user details from sn header

- context/brand-context/HISTORY.md
- context/brand-context/default/scss/40-base/block-spacing.scss
- context/brand-context/package.json
There are two outliers from a recent name spacing change for design tokens where we went from tokens-- to t- to align with how we namespace components.
> fix: updates compiled design tokens Sass variable names

- toolkits/global/packages/global-layout-grid/HISTORY.md
- toolkits/global/packages/global-layout-grid/README.md
- toolkits/global/packages/global-layout-grid/package.json
This updates a couple of cases in the readme.md where some CSS custom properties have a missing `-` in them.
This closes #805
> fix: spelling srrors

- README.md
- toolkits/global/packages/global-customer-satisfaction-input/__tests__/customer-satisfaction-input.spec.js
- toolkits/global/packages/global-customer-satisfaction-input/js/customer-satisfaction-input.js
adds the responseRating to the query string of the survey url.
uses `responseRating` which is what Jon used, but I guess it could be made configurable if anyone ever wanted something different (or to turn it off?).
> CSAT input element adds responseRating to survey url query string

- toolkits/global/packages/global-forms/HISTORY.md
- toolkits/global/packages/global-forms/package.json
- toolkits/global/packages/global-forms/view/globalFormAttributes.hbs
To prevent word suggestions from the system/keyboard **spellcheck="false"** can be added to the input field. Due to the fact spellcheck isn't listed in the globalFormAttributes it couldn't be added when using global forms. 
This shows the issue, when searching for UCL and hitting enter, results for ICL where listed.
To reproduce this, check https://staging-wayf.springernature.com/?redirect_uri=https%3A%2F%2Frd.springer.com%2Farticle%2F10.1007%2Fs10488-015-0664-7 on Safari.
> [AK] Add spellcheck attribute so it can be used as input parameter

- toolkits/global/packages/global-customer-satisfaction-input/HISTORY.md
- toolkits/global/packages/global-customer-satisfaction-input/package.json
- toolkits/global/packages/global-customer-satisfaction-input/view/customerSatisfactionInput.hbs
Removes aria-required and aria-invalid from CSAT html as not needed
The HTML elements in question already have `required` and/or `invalid` attributes on them and are the correct semantic elements
> Version 1.0.1 of Global Customer Satisfaction Input component

- toolkits/global/packages/global-customer-satisfaction-input/HISTORY.md
- toolkits/global/packages/global-customer-satisfaction-input/demo/dist/index.html
- toolkits/global/packages/global-customer-satisfaction-input/package.json
- toolkits/global/packages/global-customer-satisfaction-input/scss/50-components/_customer-satisfaction-input.scss
Issue: springernature/frontend-toolkits/issues/889
- Add `position: relative` rule to `.c-customer-satisfaction-input`
> Fix `global-customer-satisfaction-input` overflow bug
